### ISSUE TITLE
TypeError when searching for metadata

### ISSUE THREAD

**Issue by Cornul11** [mxrch/GHunt#1]
When searching for metadata, I got the following error:

> Searching metadata...
[+] 1 device found !
Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cfg)
  File "/home/dan/GHunt/lib/photos.py", line 42, in gpics
    exifeater.output()
  File "/home/dan/GHunt/lib/metadata.py", line 114, in output
    dates = print_dates(data["History"]["Valid"])
  File "/home/dan/GHunt/lib/metadata.py", line 94, in print_dates
    dates["max"] = max(dates_list).strftime("%Y/%m/%d")
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'

**Comment by mxrch** [comment]
Hello, Google Photos should not work anymore since a few days, so metadata neither.
Can I have the email you are trying to use to debug ?
Here or in private on Discord : mxrch#8507

**Comment by streger** [comment]
Moved from #26 by the repo maintainer response.

This happened also:
```
-> 1 Firmware found !
--> Picasa [2006/08/08]
Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, cfg)
  File "/someplace/GHunt/lib/photos.py", line 137, in gpics
    exifeater.output()
  File "/someplace/GHunt/lib/metadata.py", line 116, in output
    dates = print_dates(data["History"]["Valid"])
  File "/someplace/GHunt/lib/metadata.py", line 96, in print_dates
    dates["max"] = max(dates_list).strftime("%Y/%m/%d")
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by mxrch** [comment]
Thank you @streger I'm taking a look right now.
Would you contact me the email you are trying with ? Not necessary but if it's not a problem for you it'll help the debug.

**Comment by mxrch** [comment]
Apart if it's your own account and these Google photos pictures are private, it wouldn't help 😄

**Comment by streger** [comment]
@mxrch Yup, it's my private account and photos are private. First trying this on my own :)

**Comment by mxrch** [comment]
Thank you for helping debugging @streger ! This is issue is now fixed in the commit https://github.com/mxrch/GHunt/commit/d7c87d7085d67273799f44c85272cbdece5a9904, I'm closing it.
