### ISSUE TITLE
unable to get local issuer certificate 

### ISSUE THREAD

**Issue by clxtho** [mxrch/GHunt#101]
after running check_and _gen.py
i suppose somethin with the cookies?

![B8B15FC2-C33C-42E3-8701-F211C55F4617_1_105_c](https://user-images.githubusercontent.com/38918838/96106354-fd6fb200-0e8f-11eb-8b14-27cc06ca3af0.jpeg)

**Comment by mxrch** [comment]
Nope, this is a known bug with the requests, sometimes I have this problem too, I don't know how to fix it.
This is a third-party bug.
