### ISSUE TITLE
Please generate cookies and tokens first.

### ISSUE THREAD

**Issue by 1r0sh** [mxrch/GHunt#102]
Please generate cookies and tokens first.??
What should I do?

**Comment by NikolozCh** [comment]
Next time before you open issue here, please read `README.md` from [GHunt Repo](https://github.com/mxrch/GHunt).

Before you run `hunt.py`, you need to run `check_and_gen.py` got to [Accounts Google Page](https://accounts.google.com) and extract cookies  from there.

If you still can't understand what I wrote, check `README.md`.
