### ISSUE TITLE
 Message: invalid cookie domain

### ISSUE THREAD

**Issue by arthur-wxy** [mxrch/GHunt#108]
i'm sure that my cookies are all correct, 
![20201016172944](https://user-images.githubusercontent.com/39916187/96241787-39f8f600-0fd5-11eb-8c56-899e71fad27e.jpg)

after i input all the cookies, just like the pic below, how to fix this problem? plz checkout
![20201016172315](https://user-images.githubusercontent.com/39916187/96241279-8263e400-0fd4-11eb-8b15-f797a6985c91.jpg)

**Comment by mxrch** [comment]
Weird, because cookies are set to https://hangouts.google.com/robots.txt, so the domain should be good.
You're the only one getting this and I can't reproduce it.
Maybe try to add a `driver.wait(10)` after the line 72 `tmprinter.out("Setting cookies...")` (in the last updates)
