### ISSUE TITLE
Infinite loop - Google Photos

### ISSUE THREAD

**Issue by ClaeymanDamien** [mxrch/GHunt#111]
I noticed that, when there is a public folder in google images the program was looping endlessly. All other cases work perfectly except this one.

![image](https://user-images.githubusercontent.com/23224679/96288059-1c328d80-0fe3-11eb-9d3f-9ab80b47d58c.png)

![image](https://user-images.githubusercontent.com/23224679/96290402-d11a7980-0fe6-11eb-8aa1-6e810b8893db.png)

Traceback (most recent call last):            
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, config.headers, config.regexs["albums"], config.regexs["photos"],
  File "/root/Documents/Tools/Information Gathering/GHunt/lib/photos.py", line 114, in gpics
    results = re.compile(regex_albums).findall(out["source"])

**Comment by mxrch** [comment]
Yes the regex can loop indefinitly, I have to find out why and improve it.
But since Google Photos module is not used anymore, I close this issue.
