### ISSUE TITLE
id : The term 'id' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by doodlewhale** [mxrch/GHunt#113]
I try and build docker image with:
`docker build --build-arg UID=$(id -u ${USER}) --build-arg GID=$(id -g ${USER}) -t ghunt .`

I get error:
`id : The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:32
+ docker build --build-arg UID=$(id -u ${USER}) --build-arg GID=$(id -g ...
+                                ~~
    + CategoryInfo          : ObjectNotFound: (id:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
id : The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:65
+ ... r build --build-arg UID=$(id -u ${USER}) --build-arg GID=$(id -g ${US ...
+                                                                ~~
    + CategoryInfo          : ObjectNotFound: (id:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by mxrch** [comment]
@doodlewhale on which operating system you are trying it ?

**Comment by doodlewhale** [comment]
I was on win10. I have temporarily resolved this by running inside WSL 2. What is the proper command to run on win10 native?

**Comment by mxrch** [comment]
Yes the term id is not a command of Windows, now you can just pull the image from dockerhub, see the readme.
Otherwise if you want to build manually you can just "docker build . " or something like that
