### ISSUE TITLE
Doesn't detect cookies and tokens

### ISSUE THREAD

**Issue by rishit-khandelwal** [mxrch/GHunt#122]
I am using docker for running GHunt but `sudo docker run -v $(pwd)/resources:/usr/src/app/resources -ti ghunt check_and_gen.py`, I get:
```
[+] Detected stored cookies, checking it

[+] The cookies seems valid! Generating the Google Docs and Hangouts token...

Do you want to generate new Google Docs and Hangouts tokens ? (Y/n) y
Google Docs Token => ---------------------------
Authorization Token => ------------------------
Hangouts Token => ---------------------
```
and then i run ```docker run -v $(pwd)/resources:/usr/src/app/resources -ti ghunt hunt.py -----------@gmail.com`
i get `Please generate cookies and tokens first.```

**Comment by mxrch** [comment]
Hello @rishit-khandelwal, can you rebuild the docker image and retest with the last commit ?

**Comment by rishit-khandelwal** [comment]
Sorry I am late, but yeah it works with the latest commit I tried with
