### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'items' in check_and_gen.py

### ISSUE THREAD

**Issue by Antxine** [mxrch/GHunt#126]
Hello,
After entering my cookies and generating my tokens, the Google Docs token is generated and then I get this error:
> Traceback (most recent call last):
>   File "check_and_gen.py", line 158, in <module>
>     auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
>   File "check_and_gen.py", line 76, in get_hangouts_tokens
>     for k, v in cookies.items():
> AttributeError: 'bool' object has no attribute 'items'

**Comment by mxrch** [comment]
@Antxine can you `git pull` and retry ?

**Comment by Antxine** [comment]
> @Antxine can you `git pull` and retry ?

It works !!
