### ISSUE TITLE
check_and_gen.py : TypeError: __init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by Antxine** [mxrch/GHunt#127]
Hello again

I still have an error with check_and_gen.py

> Traceback (most recent call last):
> File "check_and_gen.py", line 159, in <module>
> auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
> File "check_and_gen.py", line 68, in get_hangouts_tokens
> driver = webdriver.Chrome(
> File "/home/osint/.local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
> super().__init__(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'options'

**Comment by mxrch** [comment]
Duplicate, please go in the issue #121 !
