### ISSUE TITLE
Selenium TimeoutException has occured

### ISSUE THREAD

**Issue by hawks-vision** [mxrch/GHunt#130]
[!] Selenium TimeoutException has occured. Please check your internet connection, proxies, vpns, et cetera. 

This error occurs every time when i try to load cookies and I'm sure that there is no problem with my internet connection because I'm using the same to load a 4k TV. 
I'm so eager to checkout this tool but couldn't get my hand on it due to this issue any help on this would be appriciated

**Comment by mxrch** [comment]
Hello @hawks-vision , is the program running slowly when opening the browser etc ?

**Comment by hawks-vision** [comment]
couldn't say so
