### ISSUE TITLE
print(f"[+] {len(data['matches'])} account found !")

### ISSUE THREAD

**Issue by AedenThomas** [mxrch/GHunt#132]
I'm getting this error every time

**Comment by mxrch** [comment]
I don't see error in what you sent.
Can you show me your command with the full output ?

**Comment by AedenThomas** [comment]
This is what I'm getting 
<img width="422" alt="Screen Shot 2020-10-30 at 9 54 25 AM" src="https://user-images.githubusercontent.com/18345370/97669990-5e090c80-1a96-11eb-8294-d2a2734f0d7e.png">

I can solve it only by running
`python3 hunt.py myemail@gmail.com `

**Comment by mxrch** [comment]
Yes you must use it with Python 3.
