### ISSUE TITLE
Firefox support 

### ISSUE THREAD

**Issue by advaithm** [mxrch/GHunt#142]
selenium and selenium-wire both support Firefox and it would be useful if Ghunt supported Firefox as a option.
The chromedriver-autoinstaller has a counter part for gecko based browsers geckodriver-autoinstaller

**Comment by mxrch** [comment]
I first used gecko driver but the chrome driver is so, so, so much fast, so I prefer not.

**Comment by advaithm** [comment]
should it not be possible to have a switch to chose which browser you prefer to use
