### ISSUE TITLE
Н

### ISSUE THREAD

**Issue by gucci666420** [mxrch/GHunt#143]

**Comment by mxrch** [comment]
I reported your account to GitHub, and all the following who will open empty issues or issues with spam / ads.

**Comment by ccarlos-007** [comment]
Hello There. I am new to  Github. This would be
Project and may have submitted  an empty issue or another beginners issue.
I have read instructions,  seen tutorials and still feel extremely
confused.  I welcome any tips,  instructions or tutorials you can provide.
Thnks
