### ISSUE TITLE
chromedriver_autoinstaller identified as a Chrome driver in virtualenv.

### ISSUE THREAD

**Issue by JingBh** [mxrch/GHunt#149]
I created a `virtualenv` in the project directory and installed the dependencies in it:

```bash
GHunt $ virtualenv venv
GHunt $ source ./venv/bin/activate
(venv) GHunt $ pip install -r requirements.txt
```

Then I run the program:
```bash
(venv) GHunt $ python check_and_gen.py
[-] No stored cookies found

Enter these browser cookies found at accounts.google.com:
...

[+] The cookies seems valid!
Generating the Google Docs and Hangouts token...

...
selenium.common.exceptions.WebDriverException: Message: Service ./venv/bin/chromedriver-path unexpectedly exited. Status code was: 0
```

It turns out the program searches for the driver in the project directory:
https://github.com/mxrch/GHunt/blob/493427c0d8f0f485622d16965c69a1abb16b2258/lib/utils.py#L89-L93

This should be fixed, or the program won't work in this situation.

**Comment by hugofloss** [comment]
Same problem here on MacOS Big Sur 11.1. Also using a virtualenv to install the requirements.

**Comment by agiix** [comment]
Same issue on MacOS Catalina 10.15.7 using virtualenv.

**Comment by kingpin24** [comment]
Same
