### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by Guigouu** [mxrch/GHunt#150]
Sometimes the hunt.py script raises a timeout error.
Ghunt scripts are tested in docker and directly on the host with a correct internet connection.

![image](https://user-images.githubusercontent.com/18678887/98756412-caefa100-23ca-11eb-984f-3fda994c1512.png)

**Comment by rishit-khandelwal** [comment]
This also happened with me.
![image](https://user-images.githubusercontent.com/65018379/100426712-56e61600-30b7-11eb-920f-07aedd1e7117.png)
