### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by busyH4ck3r** [mxrch/GHunt#151]
Thanks to the developers even though I can detect on some other google accounts that the program return the error when trying to scrape or gather some youtube information.
 python3 hunt.py someonesomebody@gmail.com
[+] 1 account found !

------------------------------

Name: someone somebody

Last profile edit : 2020/11/11 14:02:33 (UTC)

Email :  someonesomebody@gmail.com
Google ID : GOOGLE ID 

Hangouts Bot : No

Activated Google services :
- Youtube
- Photos
Traceback (most recent call last):
  File "hunt.py", line 97, in <module>
    data = ytb.get_channels(client, name, cfg)
  File "/root/Desktop/GHunt-master/lib/youtube.py", line 64, in get_channels
    from_youtube = youtube_channel_search(client, query)
  File "/root/Desktop/GHunt-master/lib/youtube.py", line 15, in youtube_channel_search
    data = json.loads(source.split('window["ytInitialData"] = ')[1].split('window["ytInitialPlayerResponse"]')[0].split(';\n')[0])
IndexError: list index out of range

can anyone help with this issue?

**Comment by Mikosikora** [comment]
the same

**Comment by mxrch** [comment]
Hello, I would need an email address to debug that.

**Comment by busyH4ck3r** [comment]
hi mxrch, do you need the email that I parsed during the runtime?

**Comment by progcode** [comment]
i have same error with any! email

**Comment by target111** [comment]
Same issue here, only with a slightly different error trace:
```
[+] Activated Google services :
- Youtube
Traceback (most recent call last):
  File "hunt.py", line 132, in <module>
    data = ytb.get_channels(client, name, config.data_path,
  File "/usr/src/app/lib/youtube.py", line 87, in get_channels
    from_gdocs = youtube_channel_search_gdocs(client, query, data_path, gdocs_public_doc)
  File "/usr/src/app/lib/youtube.py", line 44, in youtube_channel_search_gdocs
    search_results = gdoc_search(search_query, data_path, gdocs_public_doc)
  File "/usr/src/app/lib/search.py", line 24, in search
    title = result[0][1]
IndexError: string index out of range
```

**Comment by mxrch** [comment]
@target111 regenerate your cookies.
It means Google think you're doing an XSS attack because your cookies doesn't belongs anymore to your XSRF token.

@busyH4ck3r yes if possible

**Comment by target111** [comment]
> @target111 regenerate your cookies.
> It means Google think you're doing an XSS attack because your cookies doesn't belongs anymore to your XSRF token.
> 
> @busyH4ck3r yes if possible

Thanks, regenerating cookies worked!

**Comment by busyH4ck3r** [comment]
@target111
let me regenerate cookies too because on other emails it worked well
