### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 15: invalid continuation byte

### ISSUE THREAD

**Issue by Bapt5** [mxrch/GHunt#155]
![image](https://user-images.githubusercontent.com/63651713/99236382-6af86080-27f7-11eb-9dbe-4ad520aa357a.png)
I have this problem when I put the cookie. The program give me my Google Docs token but there is a error for the second token. Can someone help me please?

**Comment by mxrch** [comment]
I know it's been a long time you have this issue but on hundreds of users you are the only one to have this, so I can't help you, sorry.

**Comment by Bapt5** [comment]
@mxrch So I can't use your program and I don't know why.
