### ISSUE TITLE
last profile edit date 

### ISSUE THREAD

**Issue by kiiroitorii** [mxrch/GHunt#160]
It does always show last edit date as exactly 1 month ago from the time being (in case if editing was done later, it seems to be correct) no matter what cookies were used. Tried on several accounts. Running on Win10 64bit.

**Comment by kiiroitorii** [comment]
![image](https://user-images.githubusercontent.com/50533414/99929363-09d40e00-2d5e-11eb-89e6-f0e4a8c87ce3.png)
Screenshot for reference

**Comment by mxrch** [comment]
Hello @kiiroitorii, this is normal.
The last profile edit also accures when the target accept some new Google conditions / terms, or not, or just Google modifying some things.
At least it is an indicator of activity.

**Comment by kiiroitorii** [comment]
I really doubt this is normal. 1) How comes several users accept the conditions or whatsoever at the same exact second? I've put here 2 profiles for example but in fact, any profile which has activities beyond month duration will be shown as the one above.
On my understanding it just doesn't show any date longer than 1 month, in case if i'm wrong, could you show such an example please? Thank you.
