### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes :  hunt.py

### ISSUE THREAD

**Issue by bizibabe** [mxrch/GHunt#163]
Hi i have this error message on most accounts when i execute hunt.py

[+] 1 account found !

------------------------------

Couldn't find name
[-] Couldn't find name

[-] Default profile picture

Last profile edit : 2020/10/26 19:12:31 (UTC)

Email : teampaaradox@gmail.com
Google ID : 102722904180085833712

Hangouts Bot : No

[+] Activated Google services :
- Maps
Traceback (most recent call last):
  File "hunt.py", line 132, in <module>
    data = ytb.get_channels(client, name, config.data_path,
  File "/home/bizi/Documents/tools/osint/GHunt/lib/youtube.py", line 86, in get_channels
    from_youtube = youtube_channel_search(client, query)
  File "/home/bizi/Documents/tools/osint/GHunt/lib/youtube.py", line 14, in youtube_channel_search
    req = client.get(link.format(urllib.parse.quote(query)))
  File "/usr/lib/python3.8/urllib/parse.py", line 839, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.8/urllib/parse.py", line 864, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by mxrch** [comment]
Hello, I have seen this today too.
Google now removes the name from Google Maps if the target has 0 reviews.
I'll see if we can bypass it

**Comment by mxrch** [comment]
In the meantime I will deploy a patch to avoid the crash

**Comment by mxrch** [comment]
Patched crash in commit https://github.com/mxrch/GHunt/commit/8f95372a49754b5e94936ff0b50340e6a914a1db

**Comment by DT082736** [comment]
I have also encountered this issue please fix it as soon as possible

thank you

**Comment by mxrch** [comment]
> I have also encountered this issue please fix it as soon as possible
> 
> thank you
> 

Do a git pull.
