### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils'

### ISSUE THREAD

**Issue by user333222** [mxrch/GHunt#166]
I have pyhton3.7, Kali Linux Debian 9 46-bit
Google chrome installed
i've ran the requires file (python3 -m pip install -r requirements.txt)
I run the command 
python3 check_and_gen.py
or 
sudo python3 check_and_gen.py

Error:
Traceback (most recent call last):
  File "check_and_gen.py", line 13, in <module>
    from lib.utils import *
ModuleNotFoundError: No module named 'lib.utils'

Get this error when running these
sudo python3 hunt.py myemail@gmail.com
or
python3 hunt.py myemail@gmail.com

Error:
Traceback (most recent call last):
  File "hunt.py", line 17, in <module>
    from lib.banner import banner
ModuleNotFoundError: No module named 'lib.banner'

**Comment by mxrch** [comment]
Hi @user333222, can you add a __init__.py file in the lib/ directory and retry ?

**Comment by user333222** [comment]
@mxrch It worked, why did that happen? That makes no sense to me.

**Comment by mxrch** [comment]
Because sometimes Python does not recognize it as a module if there isn't this file.
I'll push a fix.

**Comment by Gripers** [comment]
> 

thank you
