### ISSUE TITLE
"This email address does not belong to a Google Account"

### ISSUE THREAD

**Issue by mxrch** [mxrch/GHunt#170]
Google changed something at this endpoint, this bug is known and I'll look for a fix.
Please don't open new issues related to this.

**Comment by cyberwr3nch** [comment]
I faced this issue right now !

**Comment by cyberwr3nch** [comment]
![image](https://user-images.githubusercontent.com/55705969/101168849-10b62700-3662-11eb-9a61-2cf020bc309a.png)

**Comment by mxrch** [comment]
Seems like the endpoint didn't changed but Google require two new cookies : the SSID and the SID.
I'll add them in the check_and_gen.py

**Comment by mxrch** [comment]
I remove the __Secure-3PSID cookie requirement because it doesn't change anything to the request anymore, and the APISID is required but you can put anything in it like a "a" and Google will accept it 🤷‍♂️ 
I'll let the APISID as a requirement to be sure

**Comment by mxrch** [comment]
Alright the fix is pushed => https://github.com/mxrch/GHunt/commit/6a83a418a353a2deb869efb1e7546534c5340295
You need to relaunch the check_and_gen.py to add the SSID & SID cookies in it.
@cyberwr3nch can you confirm that it works now ?

**Comment by cyberwr3nch** [comment]
@mxrch Made changes in the docker too ?

**Comment by blankMahir** [comment]
It seems a new problem related to this is occured after google chrome updates to 90. GHunt is not accepting cookies. after running "python3 check_and_gen.py" gives this output.

[+] Detected stored cookies, checking it

[-] Seems like the cookies are invalid.

Do you want to enter new browser cookies from accounts.google.com ? (Y/n) y
SID => 9QcpHokdoXTkPqg1NcyXP30T209POqeHmlw-30ONEQThWvN8pIZx_PAgZSk16vpd1ajzrQ.
SSID => Ap2FuAqndbdB0mKNn
APISID => pi5rauraxAdJsuZP/A8T-ahObLoxwg7Vfu
SAPISID => E-XFz1ciBExxEBU3/A2xrgBAtXKQDis2d6
HSID => A7PlmFbS5qdgF4cI3

[+] The cookies seems valid !
Traceback (most recent call last):
  File "/home/lmao/Tools/GHunt/check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/home/lmao/.local/lib/python3.9/site-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lmao/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lmao/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lmao/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lmao/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lmao/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 90.0.4430.93 with binary path /usr/bin/google-chrome

**Comment by p-hp** [comment]
I didn't run into this issue the first time I used GHunt (yahoo email on a google acc), but now it's literally unbearable. I'm unable to check any email without running into this error, even when I've confirmed the email is used in the Google account. Check for errors again?
