### ISSUE TITLE
httpx error 

### ISSUE THREAD

**Issue by Leacheck** [mxrch/GHunt#173]
Hi,

pip install httpx in any version (0.16, 0.15, etc) and installation via https://github.com/encode/httpx.git do not work. 

Would you have a solution please? 

Thanks

**Comment by Edith-panda** [comment]
hey! Leacheck this worked for me using pip 
check for latest versions for pip and python and others requirements too
pip install httpx
Collecting httpx
  Downloading httpx-0.16.1-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 145 kB/s
Requirement already satisfied: certifi in c:\users\yasha\appdata\local\programs\python\python39\lib\site-packages (from httpx) (2020.6.20)
Collecting httpcore==0.12.*
  Downloading httpcore-0.12.2-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 106 kB/s
Collecting h11==0.*
  Downloading h11-0.11.0-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 59 kB/s
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Downloading rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: idna in c:\users\yasha\appdata\local\programs\python\python39\lib\site-packages (from rfc3986[idna2008]<2,>=1.3->httpx) (2.10)
Installing collected packages: sniffio, rfc3986, h11, httpcore, httpx
Successfully installed h11-0.11.0 httpcore-0.12.2 httpx-0.16.1 rfc3986-1.4.0 sniffio-1.2.0
