### ISSUE TITLE
Selenium timeout error

### ISSUE THREAD

**Issue by permion** [mxrch/GHunt#177]
It gives "[!] Selenium TimeoutException has occured. Please check your internet connection, proxies, vpns, et cetera." error when i write cookies. Please help me.

**Comment by nashy14** [comment]
I have this same issue. I just added Ghunt to my system today. (used it before on another machine) While adding the cookies to the check_and_gen.py it accepts all of the cookies and starts but at the end it gives this error. rerun check_gen and you have to add the cookies again...and get the same result. I checked the most current updated requirements.txt and everything is as it should be according to the latest updates. Is anyone looking into why? Apparently the temp fix to the selenium-wire doesn't work for everyone. Note: I just downloaded Ghunt to this system from Github today around 3pm, so it should be the latest version.

**Comment by LevidAOL** [comment]
I appreciate you keeping me in the loop. I'm sending you the gift of luck
as a show of appreciation.

Take Care
Jesse Elizondo
Devil God Almighty
SILVER

**Comment by saduqur80** [comment]
Git diff

**Comment by saduqur80** [comment]
Contributing

**Comment by saduqur80** [comment]
Docs

**Comment by LevidAOL** [comment]
thank you. please tell malinda conway faugn i need some of the
billions i put in her account! my family and prowse family turned on
me!

**Comment by ItsMalware** [comment]
same issues
