### ISSUE TITLE
HTTPX Attribute Error : 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by ThaaoBlues** [mxrch/GHunt#186]
I have successfully registered my cookies and installed pip requirements.txt but when i run hunt.py like behind, i get this error :
![image](https://user-images.githubusercontent.com/40574784/103465283-5be35880-4d3a-11eb-9cb3-bdd6c86548f2.png)
I don't know if I missed one argument or if this is a bug. I even tried to initialize each variables user in `is_email_google_account()` with an empty string before their use but it didn't work. I hope my english is not to bad to be understandable. Have a good day.

**Comment by Suzlapulfo** [comment]
Same error here.

**Comment by CorentinSotoca** [comment]
Same error too

**Comment by jtothef** [comment]
Looks like a new version of selenium-wire was released today does not get Authorization Token properly with the way check_and_gen.py is currently written. 

Quick fix is to use older version of selenium-wire
pip install selenium-wire==2.1.2

**Comment by mxrch** [comment]
> 
> 
> Looks like a new version of selenium-wire was released today does not get Authorization Token properly with the way check_and_gen.py is currently written.
> 
> Quick fix is to use older version of selenium-wire
> pip install selenium-wire==2.1.2

I'll dig into this when I have time to update the check_and_gen.py, thanks for this quick fix.
I'll hardcode the selenium-wire version until I make the required changes !

Just before it, can someone validate the quick fix of @jtothef ?

**Comment by nacht42** [comment]
@mxrch hello,I have the same issue, and I validated that quick fix:
> pip install selenium-wire==2.1.2  

when I installed selenium-wire, the 2.1.2 version, I got `Authorization Token`, and then ghunt worked well 👍

**Comment by mxrch** [comment]
Temporary fix pushed in https://github.com/mxrch/GHunt/commit/65fb657f221a39eddecf10d8858ee90a05e76364
I let this issue opened a little bit so new users see it easily
