### ISSUE TITLE
(Question) Is it possibile to do a reverse search? Youtube channel to Google ID/E-mail.

### ISSUE THREAD

**Issue by iocomxda** [mxrch/GHunt#192]
Hi,

Is it possible to retrieve Google's ID and/or E-mail from a youtube channel link like

https://www.youtube.com/channel/XXXXX-XXXX-XXXX

If yes, could this be added in GHunt?

Sincerely.
iocomxda

**Comment by mahirbd** [comment]
Following

**Comment by mxrch** [comment]
Hello, for questions I opened a Github "Discussions" here : https://github.com/mxrch/GHunt/discussions
But nope you can't.
