### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by hunven** [mxrch/GHunt#193]
I ran "pip install httpx" and made sure I had the newest version of pip. Not sure where to go from here because I keep getting the same error when I run check and gen.

**Comment by 13827790799SJ** [comment]
maybe you can use "pip install --upgrade pip" to update python to the
newest version ,then maybe you can use "pip install  httpx"

hunven <notifications@github.com> 于2021年1月7日周四 上午4:35写道：

**Comment by mxrch** [comment]
> 
> 
> I ran "pip install httpx" and made sure I had the newest version of pip. Not sure where to go from here because I keep getting the same error when I run check and gen.

Install it with Python 3.
By default, pip use Python 2, try python3 -m pip install -r requirements.txt

**Comment by congaterori** [comment]
WARNING: The script f2py.exe is installed in 'C:\Users\DUCHUY_COMPUTER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by congaterori** [comment]
WARNING: The script f2py.exe is installed in 'C:\Users\DUCHUY_COMPUTER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by congaterori** [comment]
WARNING: The script chromedriver-path.exe is installed in 'C:\Users\DUCHUY_COMPUTER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by congaterori** [comment]
WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'C:\Users\DUCHUY_COMPUTER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
