### ISSUE TITLE
Is GHunt still working?

### ISSUE THREAD

**Issue by dontfckwithcatz** [mxrch/GHunt#197]
Hey there..

Need help at the check_and_gen.py step. I'm getting the error below:

Google Docs Token => AC4w5VhzsQZ_esfKnGcYSW4ZEqbycKC36w:1610590409216
Traceback (most recent call last):
  File "check_and_gen.py", line 159, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 68, in get_hangouts_tokens
    driver = webdriver.Chrome(
  File "/home/osint/.local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'options'

Did i miss something?

**Comment by clyde64pobo** [comment]
Can you break all that down in English for me?

**Comment by saduqur80** [comment]
Submitting change

**Comment by saduqur80** [comment]
Please manage and support

**Comment by mxrch** [comment]
Hello, be sure to have the latest version of GHunt by doing `git pull` in the GHunt folder.
And to answer you, yes it still working great.

**Comment by dontfckwithcatz** [comment]
hi, tried git pull and it states that i'm already up to date. but still getting the same error after i've put in all the correct browser cookies:

[+] The cookies seems valid !
Generating the Google Docs and Hangouts token...

Google Docs Token => AC4w5ViIG7BOHq5sj5hmDNOHEiA6zTUsxQ:1611201824960
Traceback (most recent call last):
  File "check_and_gen.py", line 159, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 68, in get_hangouts_tokens
    driver = webdriver.Chrome(
  File "/home/osint/.local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'options'

Any ideas? Thanks in advance

**Comment by saduqur80** [comment]
Ok, I'll take a look.

**Comment by mxrch** [comment]
@dontfckwithcatz try uninstalling seleniumwire and reinstalling it with the requirements.txt.
