### ISSUE TITLE
Error check_and_gen.py

### ISSUE THREAD

**Issue by TheDeathStar3** [mxrch/GHunt#200]
I got this when I try to run the check_and_gen.py file I got this:

Traceback (most recent call last):
  File "C:\Users\****\Desktop\GHunt-master\check_and_gen.py", line 8, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

am I doing something wrong?

**Comment by mxrch** [comment]
You didn't installed the requierements with python 3, see the Readme.
