### ISSUE TITLE
Please generate cookies and tokens first.

### ISSUE THREAD

**Issue by EmileDiaz** [mxrch/GHunt#201]
Newbie using this and getting a "Please generate cookies and tokens first."

I even see the instructions but cannot locate the "Dev Tools" or the "Storage Tab" under my Gmail account on Chrome Browser.

And if I do find that info, what exactly do I do with the cookies?

Can anyone help?

Thanks

ED

**Comment by mxrch** [comment]
This isn't in your Gmail Account but in your Chrome Browser.
On Chrome, `CTRL+SHIFT+i` should open the right tab.
