### ISSUE TITLE
httpx issue in ghunt.py Line no. 12

### ISSUE THREAD

**Issue by nullvoid2011** [mxrch/GHunt#202]
Even after installing all required from requirements.txt
Updatation and  and upgradation still this error is happening everytime.

┌──(nullvoid㉿kali)-[~/Downloads/GHunt]
└─sudo python3 hunt.py nullvoidhacker@gmail.com                  3 ⚙
[sudo] password for nullvoid: 
Traceback (most recent call last):
  File "/home/nullvoid/Downloads/GHunt/hunt.py", line 12, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

Please help here!

**Comment by TheKator** [comment]
Hello, I faced the same problem... I removed Ghunt from my computer, installed chrome and everything needed and after I installed it again, everything worked perfectly. (In case, u don't necessarily need sudo)

**Comment by saduqur80** [comment]
Thank you

**Comment by mxrch** [comment]
You don't need to sudo.
Make sure you installed the requirements as user if you're launching as user, or as sudo if you installed them with sudo.
