### ISSUE TITLE
KeyError "village" in metadata stage of looking through Google Photos

### ISSUE THREAD

**Issue by akari-dogman** [mxrch/GHunt#21]
During the search of metadata in Google Photos, the program will throw up a KeyError saying it can't find "village."

```
Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, cfg)
  File "C:\Users\<snip>\Downloads\GHunt-master\GHunt-master\lib\photos.py", line 134, in gpics
    exifeater.feed(img)
  File "C:\Users\<snip>\Downloads\GHunt-master\GHunt-master\lib\metadata.py", line 55, in feed
    location = self.get_GPS(img)
  File "C:\Users\<snip>\Downloads\GHunt-master\GHunt-master\lib\metadata.py", line 49, in get_GPS
    return f'{location["village"]}, {location["country"]}'
KeyError: 'village'
```

Poking through the code, I had it print out what the location was for the photos:

debug: {'amenity': '<place name>', 'road': '<road name>', 'city': 'Las Vegas', 'county': 'Clark County', 'state': 'Nevada', 'postcode': '<5 digit post code>', 'country': 'United States of America', 'country_code': 'us'}

debug: {'amenity': '<place name>', 'road': '<road name>', 'suburb': '<suburb name>', 'town': 'Paradise', 'county': 'Clark County', 'state': 'Nevada', 'postcode': '<5 digit post code>', 'country': 'United States of America', 'country_code': 'us'}

The classification of whether it's a city, village, town, or others depends on where the photo is taken. The code looks for the hardcoded "village" tag, can't find one cause the photo isnt taken in a village, and throws up a TypeError.

**Comment by mxrch** [comment]
Thank you for reporting this bug, I forgot to sanitize the location in the metadata module !
I'm pushing a fix right now.

**Comment by mxrch** [comment]
The fix is pushed ! https://github.com/mxrch/GHunt/commit/e2207159c6fe16ef1327a00fda5224dc655ffb66
I'm closing the issue.
