### ISSUE TITLE
what is the meaning

### ISSUE THREAD

**Issue by hossemtamsouh** [mxrch/GHunt#212]
$ python3.7 check_and_gen.py
Traceback (most recent call last):
  File "check_and_gen.py", line 8, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by HenkPoley** [comment]
Run this first to install httpx, among other things: https://github.com/mxrch/GHunt#2-requirements

**Comment by mxrch** [comment]
Thanks @HenkPoley !
