### ISSUE TITLE
Profile picture can be in PNG format

### ISSUE THREAD

**Issue by StigP1337** [mxrch/GHunt#213]
For the profile picture Google does not only return JPEG images, but at least PNG images, too. 
Instead of hardcoding the file ending ".jpg" in line 92 you could parse it from the image link (?) or use the build in function from PIL Image object. As you already have the Image object you could just use "format" attribute of it.

**Comment by mxrch** [comment]
Cool, I will add it.

**Comment by cyber1998** [comment]
@mxrch Hey, I am looking to contribute to my first open source project. Since this ticket isn't closed yet, I assumed it is still unresolved. May I take a look at it? :)
