### ISSUE TITLE
Slt je t ai vue sur tiktok et je suis aller installer ghunt quand je suis retourné sur tiktok je n nais pas réussi a te retrouver pour chercher un tuto de ton programme

### ISSUE THREAD

**Issue by Vickelo** [mxrch/GHunt#221]
Slt je t ai vue sur tiktok et je suis aller installer ghunt quand je suis retourné sur tiktok je n nais pas réussi a te retrouver pour chercher un tuto de ton programme

**Comment by luckyshark05** [comment]
celui qui a fait le tiktok n'a rien avoir

**Comment by mxrch** [comment]
![gif](https://media3.giphy.com/media/3o6gDRuqYeG11VeBG0/giphy.gif)
