### ISSUE TITLE
problem with check_and_gen.py , I think I don't have the hangout token

### ISSUE THREAD

**Issue by luckyshark05** [mxrch/GHunt#222]
after putting the cookies, I had this problem 

``` 
[+] The cookies seems valid !
Generating the Google Docs and Hangouts token...

Google Docs Token => AC4w5VhWhxu9Y09gB6ZhOlcrRsb8KPGYZQ:1616189634244
Traceback (most recent call last):
  File "check_and_gen.py", line 159, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 68, in get_hangouts_tokens
    driver = webdriver.Chrome(
  File "/home/luc/.local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
  File "/home/luc/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/luc/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/luc/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/luc/GHunt/chromedriver unexpectedly exited. Status code was: 127
```

**Comment by gunter423** [comment]
Hey @luckyshark05, go to directory docker/ and run python download_chromedriver.py et re run python check_and_gen.py and normaly it's work.

**Comment by Tometjazzlol** [comment]
> Hey @luckyshark05, go to directory docker/ and run python download_chromedriver.py et re run python check_and_gen.py and normaly it's work.

python: can't open file 'download_chromedriver.py': [Errno 2] No such file or directory :/

**Comment by gunter423** [comment]
> > Hey @luckyshark05, go to directory docker/ and run python download_chromedriver.py et re run python check_and_gen.py and normaly it's work.
> 
> python: can't open file 'download_chromedriver.py': [Errno 2] No such file or directory :/

put yourself in the root the directory docker/ and run python download_chromedriver.py

**Comment by Tometjazzlol** [comment]
> > > Hey @luckyshark05, go to directory docker/ and run python download_chromedriver.py et re run python check_and_gen.py and normaly it's work.
> > 
> > 
> > python: can't open file 'download_chromedriver.py': [Errno 2] No such file or directory :/
> 
> put yourself in the root the directory docker/ and run python download_chromedriver.py

Sorry but im new, and i don't know how to do that

**Comment by luckyshark05** [comment]
> Hey @luckyshark05, go to directory docker/ and run python download_chromedriver.py et re run python check_and_gen.py and normaly it's work.

same problem I have this same error
```
~/GHunt/docker$ python3 download_chromedriver.py
Traceback (most recent call last):
  File "download_chromedriver.py", line 10, in <module>
    chrome_major_version = get_major_version(get_chrome_version())
  File "/home/luc/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 107, in get_chrome_version
    with subprocess.Popen([executable_name, '--version'], stdout=subprocess.PIPE) as proc:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'
```

**Comment by gunter423** [comment]
> > Hey @luckyshark05, go to directory docker/ and run python download_chromedriver.py et re run python check_and_gen.py and normaly it's work.
> 
> same problem I have this same error
> 
> ```
> ~/GHunt/docker$ python3 download_chromedriver.py
> Traceback (most recent call last):
>   File "download_chromedriver.py", line 10, in <module>
>     chrome_major_version = get_major_version(get_chrome_version())
>   File "/home/luc/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 107, in get_chrome_version
>     with subprocess.Popen([executable_name, '--version'], stdout=subprocess.PIPE) as proc:
>   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'
> ```

Download chromium with `apt install chromium`

**Comment by paTRIBE** [comment]
I had the same issue. Fix: 
Run the script /Ghunt/docker/download_chromedriver.py (even if you are not using docker)
it will create a folder and a file: /Ghunt/docker/89/chromedriver.exe
replace the file "chromedriver.exe" from: /Ghunt/87/chromedriver.exe with the one from: /Ghunt/docker/89/chromedriver.exe
** If this did not fix your issue, copy the whole folder: /Ghunt/docker/89/ (including the .exe inside) to the /Ghunt/ folder (so you end up with /Ghunt/89/chromedriver.exe)
I think the script doesn't understand we are on the version 89 now. This fixed it for me and a friend.

**Comment by DxSper** [comment]
i think you use the script on WSL ? no ?

**Comment by Readyfreddy33** [comment]
> 
> 
> I had the same issue. Fix:
> Run the script /Ghunt/docker/download_chromedriver.py (even if you are not using docker)
> it will create a folder and a file: /Ghunt/docker/89/chromedriver.exe
> replace the file "chromedriver.exe" from: /Ghunt/87/chromedriver.exe with the one from: /Ghunt/docker/89/chromedriver.exe
> ** If this did not fix your issue, copy the whole folder: /Ghunt/docker/89/ (including the .exe inside) to the /Ghunt/ folder (so you end up with /Ghunt/89/chromedriver.exe)
> I think the script doesn't understand we are on the version 89 now. This fixed it for me and a friend.

Tried doing this but got this error:


Traceback (most recent call last):
  File "check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 89.0.4389.90 with binary path /usr/bin/google-chrome

**Comment by gunter423** [comment]
> > I had the same issue. Fix:
> > Run the script /Ghunt/docker/download_chromedriver.py (even if you are not using docker)
> > it will create a folder and a file: /Ghunt/docker/89/chromedriver.exe
> > replace the file "chromedriver.exe" from: /Ghunt/87/chromedriver.exe with the one from: /Ghunt/docker/89/chromedriver.exe
> > ** If this did not fix your issue, copy the whole folder: /Ghunt/docker/89/ (including the .exe inside) to the /Ghunt/ folder (so you end up with /Ghunt/89/chromedriver.exe)
> > I think the script doesn't understand we are on the version 89 now. This fixed it for me and a friend.
> 
> Tried doing this but got this error:
> 
> Traceback (most recent call last):
> File "check_and_gen.py", line 196, in
> driver = webdriver.Chrome(
> File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 96, in **init**
> super().**init**(*args, **kwargs)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in **init**
> RemoteWebDriver.**init**(
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in **init**
> self.start_session(capabilities, browser_profile)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
> self.error_handler.check_response(response)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
> Current browser version is 89.0.4389.90 with binary path /usr/bin/google-chrome

Change you'r version of chrome

**Comment by Readyfreddy33** [comment]
> 
> 
> > > I had the same issue. Fix:
> > > Run the script /Ghunt/docker/download_chromedriver.py (even if you are not using docker)
> > > it will create a folder and a file: /Ghunt/docker/89/chromedriver.exe
> > > replace the file "chromedriver.exe" from: /Ghunt/87/chromedriver.exe with the one from: /Ghunt/docker/89/chromedriver.exe
> > > ** If this did not fix your issue, copy the whole folder: /Ghunt/docker/89/ (including the .exe inside) to the /Ghunt/ folder (so you end up with /Ghunt/89/chromedriver.exe)
> > > I think the script doesn't understand we are on the version 89 now. This fixed it for me and a friend.
> > 
> > 
> > Tried doing this but got this error:
> > Traceback (most recent call last):
> > File "check_and_gen.py", line 196, in
> > driver = webdriver.Chrome(
> > File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 96, in **init**
> > super().**init**(*args, **kwargs)
> > File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in **init**
> > RemoteWebDriver.**init**(
> > File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in **init**
> > self.start_session(capabilities, browser_profile)
> > File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
> > response = self.execute(Command.NEW_SESSION, parameters)
> > File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
> > self.error_handler.check_response(response)
> > File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
> > Current browser version is 89.0.4389.90 with binary path /usr/bin/google-chrome
> 
> Change you'r version of chrome

I tried doing that, however i cant find the binaries to rollback. If you can find it, please point me to the right direction
