### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Kaczorekkx** [mxrch/GHunt#224]
so bassicly every time i use the check_and_gen.py it justs give me the timeout thingy I did put the timeout at config.py to 600 seconds which is 10 minutes and it still didn't work  please help

**Comment by fiuderazes** [comment]
Same problem I`ve met too - [-] Timeout while fetching the Internal tokens.

**Comment by iocomxda** [comment]
I get the timeout when trying to get the authorization header. I also tried to increase the timeout up to an hour with no luck.

**Comment by diehard88** [comment]
same here....
![Project 2](https://user-images.githubusercontent.com/25366502/113653416-c8d0fc00-9663-11eb-86f1-fc8d3e78f098.png)

**Comment by Undefined3301** [comment]
Same

**Comment by pranjal-b** [comment]
same

**Comment by 0x98a** [comment]
same

**Comment by dirt3009** [comment]
same

**Comment by diehard88** [comment]
that's it I guess
