### ISSUE TITLE
Do you plan to do type definitions?

### ISSUE THREAD

**Issue by famasoon** [mxrch/GHunt#235]
Hi,
I have 1 question.
In this repository's code was not definition type.
For example: `function(value: str) -> str`

Type definitions can prevent bugs and make it easier to know what values are needed.

Are there any plans to define types in this repository in the future?

**Comment by mxrch** [comment]
Nope, I would be cool but a little overkill for a tool like this.

**Comment by mxrch** [comment]
You're right, we should and I work on a refactor to add types definitions. It's so cool. Thanks for telling me.
