### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by bret99** [mxrch/GHunt#237]
Run 'check_and_gen.py' =>

[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => my_token
[-] Timeout while fetching the Internal tokens.                    
Please increase the timeout in config.py or try again.

Increased to 360 timeout => the same result.

**Comment by fuomag9** [comment]
same issue

**Comment by diehard88** [comment]
same here

**Comment by izdof** [comment]
same problem, did someone find how to fix that? I'm using the latest Python version
