### ISSUE TITLE
Cookie Valid but get Error

### ISSUE THREAD

**Issue by bwogi28** [mxrch/GHunt#239]
[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => XXXXXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\Music\GHunt-master\check_and_gen.py", line 212, in <module>
    internal_auth, internal_token = get_internal_tokens(driver, cookies, tmprinter)
  File "C:\Users\xxx\Downloads\Music\GHunt-master\check_and_gen.py", line 120, in get_internal_tokens
    internal_token = body.split("appsitemsuggest-pa")[1].split(",")[3].strip('"')
IndexError: list index out of range

**Comment by AngelGatewood** [comment]
This issue occurs and occurs over and over again. Someone else said to make sure you've opened Chrome at least once... I think I've used Chrome, thanks.  There is no working fix for this as far as I can tell, and nobody seems to want to give a fix for it, because nobody uses Windows anymore.

**Comment by hKQwHW** [comment]
Update Python and use `python` instead of `python3` if you're on Windows.
