### ISSUE TITLE
Docker install not identifying or saving profile photos

### ISSUE THREAD

**Issue by PlzNoJava** [mxrch/GHunt#240]
On accounts known to have a non-default profile image, docker install is resulting with "[-] Default profile picture".

I see the note as well that "[+] Docker detected, profile pictures will not be saved". Is there a way to save the photo to the system?

**Comment by mxrch** [comment]
In fact we can do it by saving the profile picture on the docker storage, but it's too complexe to find the right docker storage path for every operating system.
For Windows it's in the Linux Subsystem where Docker is emulated, etc.
If you don't need mass downloading profile pictures you can just download the profile picture from the link that GHunt gives to you.

**Comment by PlzNoJava** [comment]
The issue seems to be that the docker version reports

`[-] Default profile picture`

on accounts I can confirm there is in fact a custom profile image. Because it reports default, no link is provided to download the profile picture.
