### ISSUE TITLE
Unable to save cookies.

### ISSUE THREAD

**Issue by dathckr** [mxrch/GHunt#241]
I installed newest version on Github, and try to input cookies
My command:dat@HanhtinhLucbich ~/G/GHunt (master)> python3 check_and_gen.py
[-] No stored cookies found

Enter these browser cookies found at accounts.google.com :
SID => 9wcPB*************************************************************************************IQ.
SSID => A************************A
APISID => u***************************************0
SAPISID => ug1*********************************************************p
HSID => Apk*****************************************************************i

[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => AC4w********************************************************************009
[-] Timeout while fetching the Internal tokens.                    
Please increase the timeout in config.py or try again.
I have attemped to increase timeout from 180 to 360 (second)
But is no change.
What is the issue and solution?
If your py file have "save logs" function,please guide me.

**Comment by StigP1337** [comment]
Which Python version are you using? It works for me with Python 3.8.x and 3.9.x, but not with 3.6.x and 3.7.x (same error)

**Comment by haxor-dot** [comment]
@StigP1337 Did you tried regenerating cookies and entering them? or you using old cookies?
