### ISSUE TITLE
probable location

### ISSUE THREAD

**Issue by tsmitsmitonline** [mxrch/GHunt#243]
I have checked several times past days my own gmail account. 

I experienced during the last checks that the 'Probable location' information is missing, while on earlier checks it was presented in the results. 

Any idea why?

**Comment by mxrch** [comment]
It seems something changed for the GMaps reviews scraping, I'll take a look at it soon.
Thanks for reporting it.

**Comment by mxrch** [comment]
fixed in https://github.com/mxrch/GHunt/commit/eb25fde2d8bfa8d65176a784e7c2f013f58f85ca
