### ISSUE TITLE
Missing module named 'imagehash'

### ISSUE THREAD

**Issue by paoloq887** [mxrch/GHunt#245]
Traceback (most recent call last):
  File "ghunt.py", line 7, in <module>
    from lib.utils import *
  File "/home/altar/GHunt/lib/utils.py", line 1, in <module>
    import imagehash
ModuleNotFoundError: No module named 'imagehash'

**Comment by osint5340** [comment]
Same problem but also on file check_and_gen. py, line 14, in <module> rom lib.utilis import

You found a solution ?

**Comment by BonnY0** [comment]
pip install imagehash

**Comment by mxrch** [comment]
Just install the requirements.
