### ISSUE TITLE
Unable to run on kali/linux on a M1 / ARM

### ISSUE THREAD

**Issue by busshi** [mxrch/GHunt#246]
Hi,

Does somebody have the same issue, trying to run GHunt on a mac M1, in a virtual machine ???

WARNING : The requested image's plateform (linux/amd64) does not match the detected host plateform (linux/arm64/v8) and no specific plateform was requested
standard_init_linux_go:219:exec user process caused: exec format error

**Comment by Jrmcrpt** [comment]
Yes i try to boot from kali live live usb.
