### ISSUE TITLE
Error on Maps results

### ISSUE THREAD

**Issue by tsmitsmitonline** [mxrch/GHunt#248]
I get this (error) as a result:

Google Maps : https://www.google.com/maps/contrib/110306586906448828580/reviews
[+] 5 reviews found !             
Traceback (most recent call last):   
  File "ghunt.py", line 33, in <module>
    email_hunt(data)
  File "/usr/src/app/modules/email.py", line 160, in email_hunt
    reviews = gmaps.scrape(gaiaID, client, cookies, config, config.headers, config.regexs["review_loc_by_id"], config.headless)
  File "/usr/src/app/lib/gmaps.py", line 115, in scrape
    date = get_datetime(review.find_element_by_tag_name('div').text.split("\n")[2])
  File "/usr/src/app/lib/gmaps.py", line 22, in get_datetime
    nb = int(datepublished.split()[0])
ValueError: invalid literal for int() with base 10: '(Translated'

**Comment by mxrch** [comment]
Hi @tsmitsmitonline, can u give me the link of gmaps profile producing this error ?

**Comment by tsmitsmitonline** [comment]
Here you go: 
sudo docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt ghunt.py email timo@smit-online.nl

**Comment by mxrch** [comment]
Fixed ! :)

**Comment by tsmitsmitonline** [comment]
Great, it works!
