### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Zeb-DGSE** [mxrch/GHunt#254]
when I do python3 check_and_gen.py

**Comment by Zeb-DGSE** [comment]
![Capture d’écran 2021-06-28 à 01 42 42](https://user-images.githubusercontent.com/78049691/123562985-495e4f00-d7b2-11eb-83b1-668843b99d9a.png)

**Comment by Zeb-DGSE** [comment]
Please helpme

**Comment by gdjohn4s** [comment]
Hi,
Are you using a self-signed SSL Cert?

**Comment by Zeb-DGSE** [comment]
> Hi,
> 
> Are you using a self-signed SSL Cert?

How do I Know that ? (sorry for my lack of knowledge but I'm a brand new beginner)
