### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Venomish-Snake** [mxrch/GHunt#255]
Hi All,
I've just tried to configure the check_and_gen.py with all correct cookies etc. The google account is signed in on chrome, and all values have been entered correctly. 
I've adjusted the timeout accordingly, yet still face the same issue. All requirements are installed and i have tried using python 3.7.x, 3.8.x.

Would anyone know what the issue is?

Thanks
![image](https://user-images.githubusercontent.com/42530045/123721737-4a829f80-d8ca-11eb-96ad-fa3690c70c36.png)

**Comment by thebigelf1** [comment]
same issue as @Venomish-Snake

**Comment by Venomish-Snake** [comment]
> same issue as @Venomish-Snake

I've read somewhere that a 'fix' is using python 3.7.2 or 3.8.3. I've tried both versions and it did not work :/

**Comment by EvanSonnemans** [comment]
The problem is here : 
```
def get_internal_tokens(driver, cookies, tmprinter):
    """ Extract the mysterious token used for Internal People API
        and some Drive requests, with the Authorization header"""

    global internal_auth, internal_token

    internal_auth = ""

    tmprinter.out("Setting cookies...")
    driver.get("https://drive.google.com/robots.txt")
    for k, v in cookies.items():
        driver.add_cookie({'name': k, 'value': v})

    start = time()

    tmprinter.out("Fetching Drive homepage...")
    driver.request_interceptor = drive_interceptor
    driver.get("https://drive.google.com/drive/my-drive")

    body = driver.page_source
    internal_token = body.split("appsitemsuggest-pa")[1].split(",")[3].strip('"')

    tmprinter.out(f"Waiting for the authorization header, it "
                    "can takes a few minutes...")

    while True:
        if internal_auth and internal_token:
            tmprinter.clear()
            break
        elif time() - start > config.browser_waiting_timeout:
            tmprinter.clear()
            exit("[-] Timeout while fetching the Internal tokens.\nPlease increase the timeout in config.py or try again.")

    del driver.request_interceptor

    return internal_auth, internal_token
```
The variable internal_auth get set to "" (empty) and then ends up in an infinite loop that only ends if internal_auth is not empty. Ghunt is now broken...

**Comment by Tyrell20** [comment]
Same timeout error, both with python 3.7 and 3.8 versions.

**Comment by pierrebrtr** [comment]
Up @mxrch

**Comment by K-techie** [comment]
same timeout error 😢

**Comment by K-techie** [comment]
I had same timeout issue while trying through the git cloned package , but when i tried using Docker, it worked without any problem.

**Comment by aruso** [comment]
I'm getting the same issue with and without docker
