### ISSUE TITLE
Tells me cookies invalid

### ISSUE THREAD

**Issue by search-ish** [mxrch/GHunt#257]
I keep getting this message while using docker.
I did the same things that used to work but now it does not
can you help?
I get this message 

$ docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt check_and_gen.py
ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt ghunt.py email <email_address>
docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt ghunt.py doc <document_link>
docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt ghunt.py email <email_address>
docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt ghunt.py doc <document_link>
[-] No stored cookies found

Enter these browser cookies found at accounts.google.com :
SID => SSID => APISID => ****************j8JK
SAPISID => ************************1-A5Ou
HSID => ***************PgHn

[-] Seems like the cookies are invalid, try regenerating them.

**Comment by louissegal** [comment]
Following...
Have checked on latest version of image.
Deleted checked deleted and made new cookies from browser (Firefox) 
Attempted with Safari, issue persists.

**Comment by haxor-dot** [comment]
> Following...
> Have checked on latest version of image.
> Deleted checked deleted and made new cookies from browser (Firefox)
> Attempted with Safari, issue persists.
> 
> I am using a Google Workspace account, I am the owner of the organisation. Tomorrow I shall try with a new standard Google account, see if that makes any difference. :)

There is a issue/bug while trying to regen cookies you might face this issue #255
