### ISSUE TITLE
Running on Google Forms as well?

### ISSUE THREAD

**Issue by romulocordova** [mxrch/GHunt#258]
Just trying it out on a **public** Google Form, but i get this:

`Document ID not found.
Please make sure you have something that looks like this in your link :☺BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms`

I ran

`C:\Users\Documents\GHunt>ghunt.py doc https://docs.google.com/forms/d/e/[document ID]/viewform`

**Comment by mxrch** [comment]
It's not currently possible, Google Forms are not items that we can save on a Google Drive.
