### ISSUE TITLE
KeyError In program

### ISSUE THREAD

**Issue by ryzbaka** [mxrch/GHunt#26]
```python
Traceback (most recent call last):
  File "hunt.py", line 117, in <module>
    confidence, locations = gmaps.get_confidence(reviews, cfg)
  File "C:\Users\hamza\Desktop\GHunt\lib\gmaps.py", line 233, in get_confidence
    location = sanitize_location(location)
  File "C:\Users\hamza\Desktop\GHunt\lib\utils.py", line 29, in sanitize_location
    town = location["municipality"]
KeyError: 'municipality'
```

**Comment by ryzbaka** [comment]
I can try fixing this issue myself.

**Comment by mxrch** [comment]
Hello @ryzbaka , I can fix this issue but I'm curious, can you print the location before the "sanatize_location" line ? Because it means there is not the keys "city", "village", "town" AND "municipality", I thought it would be enough !

**Comment by streger** [comment]
Same here with village:

Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, cfg)
  File "/someplace/GHunt/lib/photos.py", line 134, in gpics
    exifeater.feed(img)
  File "/someplace/GHunt/lib/metadata.py", line 57, in feed
    location = self.get_GPS(img)
  File "/someplace/GHunt/lib/metadata.py", line 51, in get_GPS
    return f'{location["village"]}, {location["country"]}'
KeyError: 'village'

**Comment by mxrch** [comment]
@streger can you print the location before the "sanatize_location" line and put the output here ? :)

**Comment by streger** [comment]
@mxrch can you guide me where would I find that?
I seem to can't find it anywhere in the repo.

**Comment by streger** [comment]
and if you mean the line before this happened, it's:
```
Google Photos : https://get.google.com/albumarchive/...
=> x albums, y photos
```

using:
Python 3.8.2

**Comment by mxrch** [comment]
@streger  excuse me I confused your problem with the author's one, it's not the same, but effectively I understand the problem, I fix it right now.

**Comment by mxrch** [comment]
@streger fixed => https://github.com/mxrch/GHunt/commit/d927c94508c31722c4b42d48fdc2987137a5b3b8

**Comment by streger** [comment]
@mxrch Can confirm that this now passed, but failed further down the execution with:

```
-> 1 Firmware found !
--> Picasa [2006/08/08]
Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, cfg)
  File "/someplace/GHunt/lib/photos.py", line 137, in gpics
    exifeater.output()
  File "/someplace/GHunt/lib/metadata.py", line 116, in output
    dates = print_dates(data["History"]["Valid"])
  File "/someplace/GHunt/lib/metadata.py", line 96, in print_dates
    dates["max"] = max(dates_list).strftime("%Y/%m/%d")
AttributeError: 'NoneType' object has no attribute 'strftime'
```

If you want I can open new ticket for this?

**Comment by mxrch** [comment]
@streger seems like you have the same error of https://github.com/mxrch/GHunt/issues/1, can you please move to this issue so we keep issues clean ? 😄

**Comment by mxrch** [comment]
Issue fixed in => https://github.com/mxrch/GHunt/commit/8fd45a1071b48d6d62c85d84285e22e20c41c247, I'm closing this issue.
