### ISSUE TITLE
check_and_gen.py: List index out of range

### ISSUE THREAD

**Issue by nlguerra2003** [mxrch/GHunt#261]
This is my first use of the program, and I expected a stdin to input the cookies.
Instead, this error is displayed:
![image](https://user-images.githubusercontent.com/25437891/128834214-cb0ec418-508d-40c3-a5d8-812cf45c996d.png)

**Comment by Cambysses** [comment]
I had this problem today, chromedriver_autoinstaller grabs the version number from a user registry key which does not exist unless you have launched Chrome at least once.

So if you launch Chrome as the particular user that is running the script it should fix it.
