### ISSUE TITLE
Version not supported 

### ISSUE THREAD

**Issue by theextremecoder** [mxrch/GHunt#27]
Hey,
I'm on Windows 10
When I try to execute the command "python hunt.py myemail@gmail.com" on CMD, it doesn't give any output.
So I tried to execute hunt.py. It gives :
`C:\Users\*****\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "`
And the python console closes itself.
I can't fix it myself. Can anyone Help me ?

**Comment by mxrch** [comment]
Hello @theextremecoder , it seems to be related to the `requests` module.
Can you try this : `pip install --upgrade requests` and tell me if it fixes the error ?
You'll need to adapt the command depending on how you installed the requirements, like adding `sudo` at the beginning or `--user` at the end.

Reference : https://github.com/streamlink/streamlink/issues/2448

**Comment by Kh4l1l-C0d3** [comment]
Hi !
Thank you for helping me,
Yes, I fixed the problem,
Sorry for responding late
