### ISSUE TITLE
Youtube Links

### ISSUE THREAD

**Issue by mgmehra2005** [mxrch/GHunt#278]
<b>Youtube</b> links are not opening. It's showing error.

*    Invalid url forwarding parameter.
*    Sorry, your login was incorrect.

**Comment by beedell-roke** [comment]
I've the same, when attempting to switch accounts. [^1]

[^1]: [`reddit.com/r/youtube/s/gveFF7J6Mx`](https://www.reddit.com/r/youtube/s/gveFF7J6Mx)
