### ISSUE TITLE
params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})} KeyError: 'value'

### ISSUE THREAD

**Issue by HellGateCorp** [mxrch/GHunt#283]
Chrome, chromedriver and Selenium are up to date but after the last update, when I input my valid Cookies-Keys it throw the ErrorCode below . The curious is, after it I must reboot my System for the possibility to open Chrome again, when I don't reboot it I can click on to the icon but nothing happens. Now when I want to take the ChromeApp into the Garbage, the OS won't do it and show me an error "can't be deleted because its seems to be opened" ... Have anybody an Idea ??
Greetz

Error Output for **check_and_gen.py**:

Generating OSID for the Cloud Console...
Traceback (most recent call last):
  File "/Users/XXX/Tools/INVEST/GOO/GHunt/check_and_gen.py", line 290, in <module>
    osid = gen_osid(cookies, "console.cloud.google.com", "cloudconsole")
  File "/Users/XXX/Tools/INVEST/GOO/GHunt/check_and_gen.py", line 152, in gen_osid
    params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})}
  File "/Users/XXX/Tools/INVEST/GOO/GHunt/check_and_gen.py", line 152, in <dictcomp>
    params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})}
KeyError: 'value'

**Comment by Wendelstein7** [comment]
I can confirm I am getting this exact error with the most recent docker container. I am not sure why the issue is closed.

I pulled the docker container and then ran the check_and_gen.py script using the commands given in the readme.md.
I pasted all the cookies except for LSID, which wasn't present.
It then reports that cookies were valid and it fails at generating cloud console OSID.

```
Choice => 3
SID => XXX
SSID => XXX
APISID => XXX
SAPISID => XXX
HSID => XXX
LSID => 
__Secure-3PSID => XXX

[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => XXX
Generating OSID for the Cloud Console...
Traceback (most recent call last):
  File "check_and_gen.py", line 290, in <module>
    osid = gen_osid(cookies, "console.cloud.google.com", "cloudconsole")
  File "check_and_gen.py", line 152, in gen_osid
    params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})}
  File "check_and_gen.py", line 152, in <dictcomp>
    params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})}
KeyError: 'value'
user@machine:~
```

**Comment by HellGateCorp** [comment]
I'm not sure what happened behind the scenes there, but I can tell you how I solved this problem. First, we need a recent Chrome or Brave browser instance that is not corrupted. From there we can now download the "GHunt Companion" hosted extension from the official Chrome webstore. This tool can extract the whole stack of needed attributes from the auto-detected cookie and turn it into a Base64 encoded string, which we now need to copy. Then we start the Docker Daemon, open a new terminal session and navigate to the home directory of $Ghunt. From there we run the BASH script “check_and_gen.sh”, which now gives us the option to choose the option to feed the daemon running and hungry in the background with our base64 string pinned in the copyboard. After the bloody cookie dinner, you should be able to launch the Docker-based GHunt.sh bashscript without throwing an exception. If I'm not entirely mistaken, the issue was triggered by the last cookie attribute to be entered, which references your YouTube account. I hope it will help you to fix this problem. Regards
