### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by MrNonoss** [mxrch/GHunt#285]
Hi there, 

I noticed the [docker image](https://hub.docker.com/r/mxrch/ghunt) is 3 months old and the source here is only a few days. 
The doc states a new image is built upon each git push, but I wonder if something is broken and unnoticed.

For exemple, the check_and_gen.py in docker image does not integrate browser extension companion.

**Comment by mxrch** [comment]
Thanks for letting me know, dockerhub seems to have moved the auto-build functionnalty to pro-members, so I moved GHunt on the Github Containers Registry (ghcr.io) and auto-build with Github Actions, it should be good ! https://github.com/mxrch/GHunt/pkgs/container/ghunt
