### ISSUE TITLE
Ghunt Companion (Browser Extension) only gives me a long string

### ISSUE THREAD

**Issue by romulocordova** [mxrch/GHunt#287]
As I couldn't find the LSID, I installed the GHunt Companion so I can get the cookies.

Nevertheless, I just get a very long string of characters and when running `python3 check_and_gen.py` it asks for more than one string.

Help.

**Comment by mxrch** [comment]
> As I couldn't find the LSID, I installed the GHunt Companion so I can get the cookies.
> 
> Nevertheless, I just get a very long string of characters and when running `python3 check_and_gen.py` it asks for more than one string.
> 
> Help.

Are you sure you got the latest version of GHunt ? Run a "git pull" in the folder, and when you run the check_and_gen.py, it should ask you the method to use to login
Here you can choose between the two methods of the extension, or the manual method.

**Comment by romulocordova** [comment]
> > As I couldn't find the LSID, I installed the GHunt Companion so I can get the cookies.
> > Nevertheless, I just get a very long string of characters and when running `python3 check_and_gen.py` it asks for more than one string.
> > Help.
> 
> Are you sure you got the latest version of GHunt ? Run a "git pull" in the folder, and when you run the check_and_gen.py, it should ask you the method to use to login Here you can choose between the two methods of the extension, or the manual method.

Worked like a charm. Thanks!
