### ISSUE TITLE
No LSID on cookies

### ISSUE THREAD

**Issue by kevinalfito69** [mxrch/GHunt#291]
![image](https://user-images.githubusercontent.com/71138490/141940600-775c6c74-5677-4e9a-a4c1-d747133dd535.png)
I have tried in several browsers but still not found a cookie named LSID

and when I try to use cookies base 64, from the chrome extension there is an error:
[-] Timeout while fetching the Internal tokens.
Please increase the timeout in config.py or try again.

**Comment by mxrch** [comment]
If you look at the Readme you'll see that the LSID isn't from myaccount.google.com but from accounts.google.com, which redirects to myaccount.google.com, so you'll not be able to fetch it with an extension like Cookie Editor, you shouls look in the requests.
If you have a timeout error by using the base64, it's another problem and I don't know why it's happening.

**Comment by K-techie** [comment]
>I have tried in several browsers but still not found a cookie named LSID
I found the LSID by checking the "Show filtered out request cookies" box refer below issue.
https://github.com/mxrch/GHunt/issues/205#issuecomment-968823108.
But even after entering the LSID i could get the same timeout error as copying the base64 would give me

**Comment by K-techie** [comment]
> If you look at the Readme you'll see that the LSID isn't from myaccount.google.com but from accounts.google.com, which redirects to myaccount.google.com, so you'll not be able to fetch it with an extension like Cookie Editor, you should look in the requests. If you have a timeout error by using the base64, it's another problem and I don't know why it's happening.

Sir , regarding the timeout issue , i faced the same problem. But apparently ghunt works without any error with the help of docker image.

**Comment by zakzico** [comment]
If you're using google chrome, go to Settings, Privacy and Security, Cookies and other site data, Search or Find " accounts.google.com " and click on it. BAM! LSID will be displayed. Copy the Content section and paste it in Ghunt LSID>> . 

Let me know if it worked!

**Comment by kevinalfito69** [comment]
> If you're using google chrome, go to Settings, Privacy and Security, Cookies and other site data, Search or Find " accounts.google.com " and click on it. BAM! LSID will be displayed. Copy the Content section and paste it in Ghunt LSID>> .
> 
> Let me know if it worked!

Thanks its work

**Comment by AaryanK3304** [comment]
in 2022, currently, this method isn't working. any other solution, please

**Comment by karano-techie** [comment]
> in 2022, currently, this method isn't working. any other solution, please 

better use the browser extension then

**Comment by kevinalfito69** [comment]
Try using this extension https://chrome.google.com/webstore/detail/editthiscookie
