### ISSUE TITLE
No OSID header detected, exiting

### ISSUE THREAD

**Issue by mixtraff** [mxrch/GHunt#292]
Hi,
I get this message in terminal. 
```
Generating OSID for the Cloud Console...
[-] No OSID header detected, exiting...
```
After this warning about OSID, I cannot continue to make research by email. 
I get message after request `python3 ghunt.py email xxxx@google.com`
`Please generate cookies and tokens first, with the check_and_gen.py script.`
How to fix this problem?
Thanks

**Comment by s-cr0w** [comment]
Same issue for me...

Generating OSID for the Cloud Console...                                                                                                                                
[-] Timeout while fetching the Internal tokens.                                                                                                                         
Please increase the timeout in config.py or try again.

**Comment by mxrch** [comment]
I can't reproduce the issue for the moment, so I can't help a lot on this currently :/
Are these new accounts ?

**Comment by mixtraff** [comment]
When I try to use default config I see messege:

Generating OSID for the Cloud Console...                                                                                                                                
[-] Timeout while fetching the Internal tokens.                                                                                                                         
Please increase the timeout in config.py or try again. 

But If I use same headers config with my browswer:

`headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4509.0 Safari/537.36',
    'Connection': 'keep-alive',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language':'ru,en-US;q=0.5',
    'Cache-Control':'no-cache',
    'Pragma':'no-cache'
}`

**Comment by swiss-kn9fe** [comment]
Almost a year later and no fix. I get the same error message

**Comment by mxrch** [comment]
@swiss-kn9fe
> *Almost a year later and still no fix. I get the same error message :(*
I asked a question to get more details and maybe reproducing the issues, I got no response. So don't cry
