### ISSUE TITLE
Type Error after generating the Google Docs Token

### ISSUE THREAD

**Issue by KrishSai1997** [mxrch/GHunt#3]
┌─[✗]─[XYZ@parrot]─[/opt/GHunt]
└──╼ $python3 check_and_gen.py
__Secure-3PSID => REDACTED
APISID => REDACTED
SAPISID => REDACTED
HSID => REDACTED

[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => REDACTED
Traceback (most recent call last):
  File "check_and_gen.py", line 74, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'options'

┌─[✗]─[XYZ@parrot]─[/opt/GHunt]
└──╼ $python3 --version
Python 3.8.5

#After trying to run it with sudo, I got the Following Error:

[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => REDACTED
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_and_gen.py", line 74, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

#I have the "chromedriver" executable in my current directory. And even added it to my PATH variable.

┌─[✗]─[XYZ@parrot]─[/opt/GHunt]
└──╼ $echo $PATH
/home/XYZ/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/GHunt/chromedriver

**Comment by Collin-St** [comment]
I had this issue. For me, it was related to line 74:
```py
driverpath = get_driverpath()
```
I don't know what function the author intended to call here, but it doesn't exist. I replaced it with a hardcoded path:
```py
driverpath = './chromedriver'
```

Depending on which OS you're on, you might also run into a permissions error after you fix that.

**Comment by mxrch** [comment]
@KrishSai1997 @Collin-St can I know from which folder you are launching the script ?
You must be in the ghunt folder, because it searches the chromedriver with a relativepath, so from where you are located.

About the get_driverpath function, it is in the lib/utils.py file, and I import it at the beggining of check_and_gen.py, so I think you are not well located when running the scripts.

**Comment by Collin-St** [comment]
@mxrch 
I'm working in the correct directory structure. But now I see the real issue:

in `lib/utils.py` ln 37, `driverpath = "chromedriver"` should be `driverpath = "./chromedriver"`

This solved the problem for me as well without hardcoding the driver path in `check_and_gen.py`. I assume you developed this on a Windows machine, so you didn't run into this issue.

**Comment by mxrch** [comment]
Ok thank you, I'll test this edit on Windows right now and push a fix if it's okay. 😊

**Comment by mxrch** [comment]
https://github.com/mxrch/GHunt/commit/d2c77ffb634edff680a3e345814c45ef6a164042

This should be good now.
