### ISSUE TITLE
KeyError: 'twoColumnSearchResultsRenderer'

### ISSUE THREAD

**Issue by wagnandreas** [mxrch/GHunt#30]
On calling `python3 hunt.py info@stadtmarketing-traunstein.de` :
```
Unable to fetch connected Google services.
Traceback (most recent call last):
  File "hunt.py", line 97, in <module>
    data = ytb.get_channels(client, name, cfg)
  File "/home/andreas/Desktop/GHunt/lib/youtube.py", line 64, in get_channels
    from_youtube = youtube_channel_search(client, query)
  File "/home/andreas/Desktop/GHunt/lib/youtube.py", line 16, in youtube_channel_search
    channels = data["contents"]["twoColumnSearchResultsRenderer"]["primaryContents"]["sectionListRenderer"]["contents"][0]["itemSectionRenderer"]["contents"]
KeyError: 'twoColumnSearchResultsRenderer'
```

**Comment by mxrch** [comment]
> 
> 
> Uhm, that's not a gmail address. GHunt specifically requires a gmail address

@PinkDev1 nope 😄 it works too if someone created his Google Accounts with the email from another provider

**Comment by mxrch** [comment]
I'm looking at this

**Comment by wagnandreas** [comment]
> Uhm, that's not a gmail address. GHunt specifically requires a gmail address

it's a GSuit account i think

**Comment by mxrch** [comment]
Yeah this is an interesting catch, this account doesn't even have a name.

**Comment by mxrch** [comment]
![image](https://user-images.githubusercontent.com/17338428/95106470-d9e29400-0738-11eb-933d-4d1a1d7be858.png)

**Comment by mxrch** [comment]
Error fixed in https://github.com/mxrch/GHunt/commit/ddd2ccd2d62cdfb3fcddd08c7b1136a9f715bf60, I'm closing this issue.
