### ISSUE TITLE
hey  gunter423

### ISSUE THREAD

**Issue by app188** [mxrch/GHunt#301]
Please generate cookies and tokens first, with the check_and_gen.py script.

**Comment by mxrch** [comment]
?

**Comment by app188** [comment]
this is the problem how can i fix it #300  Please generate cookies and tokens first, with the check_and_gen.py script.

**Comment by mxrch** [comment]
It's not the problem, it's literally the solution.
Just, do what it says.

And please, before running a project, **read the README instructions.**
