### ISSUE TITLE
Where can I find LSID?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [mxrch/GHunt#302]
It says to enter LSID but I don't see it anywhere in my cookies.
I am using KALI App.
It was working and randomly stopped. Any ideas?

**Comment by mxrch** [comment]
> It was working and randomly stopped
Are you an old user ? The cookies extractions has changed since a few months, you can check the readme to know how to do it.
Make sure your GHunt is updated by doing a `git pull`.
It's recommended to use the browser extension to sync your Google account with GHunt.

**Comment by ZekePolarisBSH** [comment]
Yea at old user and I noticed that it uses the plugin now and I started using that but it keeps getting stuck. And I read the readme. It could be my browser since my ISP is saying my browser has issues. Well many websites says the same thing but using different words.... First it was saying, "Starting browser..." for hours. And now it is saying "Setting cookies..." Should I keep trying?

**Comment by ZekePolarisBSH** [comment]
New issue with requirements. It says type py, but I have to type python3.

**Comment by ZekePolarisBSH** [comment]
Oh no it says missing something. goepy? Wait wut?

**Comment by mxrch** [comment]
> New issue with requirements. It says type py, but I have to type python3.

It says python3 for Unix and py for Windows.
Don't you said you're on Kali Linux ?

**Comment by mxrch** [comment]
> Oh no it says missing something. goepy? Wait wut?

Do you want to say geopy ?

**Comment by ZekePolarisBSH** [comment]
> > New issue with requirements. It says type py, but I have to type python3.
> 
> It says python3 for Unix and py for Windows. Don't you said you're on Kali Linux ?

Yea KALI Linux the app for Windows 10.

**Comment by ZekePolarisBSH** [comment]
> > Oh no it says missing something. goepy? Wait wut?
> 
> Are you talking about geopy ?

Yea it says that is missing and to use requirements "--update" and I did but it keeps saying to use the command again when I try to run verify gen. It has to have something to dobwith my device or internet because everything did started to mess up after my ISP said something. Idk though.....

**Comment by mxrch** [comment]
> > > New issue with requirements. It says type py, but I have to type python3.
> > 
> > It says python3 for Unix and py for Windows. Don't you said you're on Kali Linux ?
> 
> Yea KALI Linux the app for Windows 10.

The Kali Linux app works on the Windows Subsystem Linux (WSL), so please considering you're on a Unix environment when reading instructions.

**Comment by ZekePolarisBSH** [comment]
> > > > New issue with requirements. It says type py, but I have to type python3.
> > > 
> > > 
> > > It says python3 for Unix and py for Windows. Don't you said you're on Kali Linux ?
> > 
> > 
> > Yea KALI Linux the app for Windows 10.
> 
> The Kali Linux app works on the Windows Subsystem Linux (WSL), so please considering you're on a Unix environment when reading instructions.

Oh ok so use the unix method and not the Windows method. Wait there is a Windows Kali? I thought the one I been using was Windows Kali this whole time. Thanks Microsoft for misinforming users!!!

**Comment by mxrch** [comment]
> > > Oh no it says missing something. goepy? Wait wut?
> > 
> > Are you talking about geopy ?
> 
> Yea it says that is missing and to use requirements "--update" and I did but it keeps saying to use the command again when I try to run verify gen. It has to have something to dobwith my device or internet because everything did started to mess up after my ISP said something. Idk though.....

Are you sure your libs upgrade does not fail ? Please provide output of your upgrade

**Comment by ZekePolarisBSH** [comment]
> > > > Oh no it says missing something. goepy? Wait wut?
> > > 
> > > 
> > > Are you talking about geopy ?
> > 
> > 
> > Yea it says that is missing and to use requirements "--update" and I did but it keeps saying to use the command again when I try to run verify gen. It has to have something to dobwith my device or internet because everything did started to mess up after my ISP said something. Idk though.....
> 
> Are you sure your libs upgrade does not fail ? Please provide output of your upgrade

I will once I get back to my laptop. Busy at the moment. Also thanks for replying not many devs reply to me much. I just get bots. LOL

**Comment by ZekePolarisBSH** [comment]
I just realized that I didn't run it, anything, as root. Oops......................... Everything good now LOL sorry that I bothered you.

**Comment by ZekePolarisBSH** [comment]
Hey um, after using this tool the first time, all the sudden I get an email in my gmail the same day, threatening me for bitcoin.

**Comment by mxrch** [comment]
> Hey um, after using this tool the first time, all the sudden I get an email in my gmail the same day, threatening me for bitcoin.

1) You're off-topic
2) The tool is open-source. Read the code and you'll see that your email is not used on any third-party site than Google.

**Comment by ZekePolarisBSH** [comment]
> > Hey um, after using this tool the first time, all the sudden I get an email in my gmail the same day, threatening me for bitcoin.
> 
> 1. You're off-topic
> 2. The tool is open-source. Read the code and you'll see that your email is not used on any third-party site than Google.

I was just saying, the odds of this happening are very slim and I never said anything about the tool having my email in it. It happened right after getting the tool to go.

**Comment by ZekePolarisBSH** [comment]
Also most cases open source is not a good thing. Also the code in a tool is not always a threat as even requirements can be used as a threat. I saw it happen before.
