### ISSUE TITLE
check_and_gen.py: list index out of range

### ISSUE THREAD

**Issue by Sonpr0x** [mxrch/GHunt#304]
Python 3.10.1

Traceback (most recent call last):
  File "G:\osint\GHunt-master\check_and_gen.py", line 294, in <module>
    internal_auth, internal_token = get_internal_tokens(driver, cookies_with_osid, tmprinter)
  File "G:\osint\GHunt-master\check_and_gen.py", line 129, in get_internal_tokens
    internal_token = body.split("appsitemsuggest-pa")[1].split(",")[3].strip('"')
IndexError: list index out of range

![ảnh](https://user-images.githubusercontent.com/82546097/146543457-453b456a-f2d4-4f5a-8e41-b2f9e1970e53.png)

**Comment by mxrch** [comment]
Can you check if you have the string "appsitemsuggest-pa" in the req.text of drive.google.com ?

**Comment by Sonpr0x** [comment]
I couldn't find "req.text" or "appsitemsuggest-pa" in the cookie or path of drive.google.com, can u give me a hint?

**Comment by KawKum** [comment]
> Can you check if you have the string "appsitemsuggest-pa" in the req.text of drive.google.com ?

I also have the same problem. When i check drive.google.com, yes there are request to appsitemsuggest-pa.clients6.google.com

**Comment by Genialngash** [comment]
Am still facing a similar issue.Any fix?

**Comment by hackerkartel64** [comment]
Anyone going to solve this ??

**Comment by mxrch** [comment]
Hello, I can reproduce this issue now (and many users too as I see), so I'm fixing it now.

**Comment by mxrch** [comment]
Fixed in https://github.com/mxrch/GHunt/commit/85100f2698378f5c7e000d02f1367521ee339598.
