### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RosyHorus** [mxrch/GHunt#305]
```
Traceback (most recent call last):
  File "ghunt.py", line 3, in <module>
    from lib import modwall; modwall.check() # We check the requirements
  File "/home/gaymeryosr/ghunt/lib/modwall.py", line 29
    if req["specs"] and (specs := req["specs"][0]):
                               ^
SyntaxError: invalid syntax
```

**Screenshots**
![image](https://user-images.githubusercontent.com/71973467/146674862-09cd03ca-78d2-4c09-93ac-83118644f38b.png)

 - Google Cloud (windows 10)
 - Python 3.7.3

**Comment by mxrch** [comment]
It uses the walrus operator, so it requires Python 3.8+ :)

**Comment by RosyHorus** [comment]
> It uses the walrus operator, so it requires Python 3.8+ :)

Yeah I just saw that on Readme.. I thought at first it only requires python 3.7 :D 
thx!
