### ISSUE TITLE
not running Ghunt .. cookies and token ......pls help kindly... 

### ISSUE THREAD

**Issue by sridhar-gif** [mxrch/GHunt#308]
┌──(kali㉿kali)-[~/GHunt]
└─$ ./check_and_gen.py                   
[-] No stored cookies found

You can facilitate configuring GHunt by using the GHunt Companion extension on Firefox, Chrome, Edge and Opera here :
=> https://github.com/mxrch/ghunt_companion

[1] (Companion) Put GHunt on listening mode (currently not compatible with docker)
[2] (Companion) Paste base64-encoded cookies
[3] Enter manually all cookies

Choice => 3
SID => GggS90p0jFMChgAmQA2CIiOrX-D9D5bTjIdkEbs6sZRESR87XAynrakq8wo_-Ovv2cmGbQ.
SSID => A4MzjalJnCplboTgp
APISID => 8MjIdt76SBIwHNdu/A95XQUgrbY9yd_DtJ
SAPISID => IzNbVy4Wc9CiI5VP/A7QYRJMsPFNoto3MU
HSID => AI3vDOibLqqOa-zbS
LSID => 
__Secure-3PSID => GggS90p0jFMChgAmQA2CIiOrX-D9D5bTjIdkEbs6sZRESR871e14ivF5tX_PxKExJuzoGw 

[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => AC4w5Vjj2_LBwtK9tUHLLRHql-3Kugv8Vw:1643439930942
Generating OSID for the Cloud Console...
Traceback (most recent call last):
  File "/home/kali/GHunt/./check_and_gen.py", line 290, in <module>
    osid = gen_osid(cookies, "console.cloud.google.com", "cloudconsole")
  File "/home/kali/GHunt/./check_and_gen.py", line 152, in gen_osid
    params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})}
  File "/home/kali/GHunt/./check_and_gen.py", line 152, in <dictcomp>
    params = {x.attrs["name"]:x.attrs["value"] for x in body.find_all("input", {"type":"hidden"})}
KeyError: 'value'

(kali㉿kali)-[~/GHunt]
└─$ ./ghunt.py email ramsri7974@gmail.com

       
Please generate cookies and tokens first, with the check_and_gen.py script.

**Comment by taonix** [comment]
+1

**Comment by younrx** [comment]
Same issue. Tried with Chrome, Firefox and Edge, with various google accounts. Re-cloning repo doesn't change anything. I tried with version at commit 00656c8 (Jun 4, 2022) which was the most recent when I cloned the repo.

**Comment by userghana** [comment]
same problem
