### ISSUE TITLE
This email address does not belong to a Google Account.

### ISSUE THREAD

**Issue by blackcatpro777** [mxrch/GHunt#31]
Hi, only first time it worked. from second time, it always throws "This email address does not belong to a Google Account."

**Comment by mxrch** [comment]
Hello @blackcatpro777 , can I have more information ? Like the email you are trying with ?
What you are descripting seems impossible, that an email is marked as valid and sometimes not.

**Comment by blackcatpro777** [comment]
The email is valid, it worked first time. When I tried the same email address second time, it throws "This email address does not belong to a Google Account." and no other emails are working now.

**Comment by l4zy0n3** [comment]
printing the response gave out
`
{'error': {'code': 401, 'message': 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.', 'status': 'UNAUTHENTICATED'}} [-] This email address does not belong to a Google Account.
`
Regenerating the cookies worked for me, seems like an intermittent issue

**Comment by l4zy0n3** [comment]
> printing the response gave out
> `{'error': {'code': 401, 'message': 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.', 'status': 'UNAUTHENTICATED'}} [-] This email address does not belong to a Google Account.`
> Regenerating the cookies worked for me, seems like an intermittent issue

PS : I was logged into multiple accounts on the first try
Logged out of all accounts and logged back into one specific account
Then regenerated the cookies

**Comment by PinkDev1** [comment]
Seems like a K20 issue. @mxrch just close this

**Comment by mxrch** [comment]
@blackcatpro777 please register your cookies again and retry.
