### ISSUE TITLE
Error: sudo python3 check_and_gen.py

### ISSUE THREAD

**Issue by andre-santos1** [mxrch/GHunt#312]
When I run "sudo python3 check_and_gen.py" I get the following error:

Traceback (most recent call last):
  File "/home/kali/ghunt/check_and_gen.py", line 14, in <module>
    from seleniumwire import webdriver
  File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 14, in <module>
    from selenium.webdriver import TouchActions  # noqa
ImportError: cannot import name 'TouchActions' from 'selenium.webdriver' (/usr/local/lib/python3.9/dist-packages/selenium/webdriver/__init__.py)

No luck Googling it... Anyone can help me?

**Comment by HenkPoley** [comment]
Unsure, but maybe you need to update selenium-wire? https://pypi.org/project/selenium-wire/

See History > 4.6.2

**Comment by andre-santos1** [comment]
Great!!!!1 Thanks!!! Now I have a cookies problem... I´ll search for a solution

Thanks
