### ISSUE TITLE
line 220, 214 issue. Typeerror: take 2 but 5 given

### ISSUE THREAD

**Issue by onikafei** [mxrch/GHunt#320]
![kali error](https://user-images.githubusercontent.com/42854104/160257560-5aadcfd6-b0a0-4ac8-9ff4-66cf6a13d2b7.jpg)
I cant figure it out, maybe Im missing a big driver as I just installed it but I cant find a fix.

**Comment by HenkPoley** [comment]
Caused by this webdriver-manager patch (look for `def find_driver`): https://github.com/SergeyPirogov/webdriver_manager/commit/43e0feddb2a49b212d61a1547c4ab0623c8431a3#diff-ef9532cdbb96a52c9b3b2327d957ef9eb4b6c1ca69ed3a83c4dc27b5b3d78eaaR70

It is at least in webdriver-manager 3.5.4
