### ISSUE TITLE
Selenium TimeoutException has occured error ???

### ISSUE THREAD

**Issue by haszimoto** [mxrch/GHunt#321]
"[!] Selenium TimeoutException has occured. Please check your internet connection, proxies, vpns, et cetera." error when i write cookies. Please help me.

**Comment by SSean08** [comment]
Got them also after
waiting for the /v2/people/me/blockedPeople request, it can takes a few minutes...
[!] Selenium TimeoutException has occured. Please check your internet connection, proxies, vpns, et cetera.

**Comment by LETIFERUM** [comment]
same...

**Comment by pavlosidelov** [comment]
Same

**Comment by xasser** [comment]
same here

**Comment by Midoran** [comment]
Same. Is there a solution.

**Comment by justekoro** [comment]
same here

**Comment by francoborgia** [comment]
same problem even with latest updates

**Comment by hackerkartel64** [comment]
hey men, anyone with a solution we can try ?????
you can mail me at hackerkartel64@gmail.com

**Comment by mxrch** [comment]
fixed in issue https://github.com/mxrch/GHunt/issues/321.
Looks like Hangouts has changed something.

**Comment by justekoro** [comment]
thank you!

**Comment by alonsoir** [comment]
Thanks man, it is working again in kali.

**Comment by hackerkartel64** [comment]
after too long struggling guys i came out with a solution. Don't know if it will work for each of you, btw i use kali. so the solution is you should install or update python enviroment, then boom. we are in.
commands:
apt-get -y install virtualenv   
if the above didn't work use 
apt-get install virtualenv

**Comment by haszimoto** [comment]
Guys after fix ... working but now is same problem.

I think if selnium is updated this problem repeats :/

ps.virtualenv not working for me
