### ISSUE TITLE
Ghunt issue

### ISSUE THREAD

**Issue by SpiriteAway** [mxrch/GHunt#324]
Hello, I have a problem, I install two different python (python 3.8 and 3.10) because I need it for two different programs. Except that when I want to run GHunt on python 3.10, it puts it on 3.8. Is there any way I can get the program started on 3.10 and not 3.8?

$ python ghunt email test@gmail.com
C:\Program Files\Python38\python.exe: can't find '__main__' module in 'ghunt'

**Comment by mxrch** [comment]
Hello, it's related to your environment variables and isn't related to GHunt.
I think you should use update-alternatives to update your Python links.
