### ISSUE TITLE
check_and_gen.py error on run

### ISSUE THREAD

**Issue by jevarlet** [mxrch/GHunt#327]
The following error occurs when running check_and_gen.py (on process start, before any cookie input)

   > .../ghunt/lib/utils.py", line 214, in get_driverpath
    driverpath = chromedrivermanager_silent.driver_cache.find_driver(driver)
TypeError: find_driver() missing 3 required positional arguments: 'driver_name', 'os_type', and 'driver_version'

**Comment by HenkPoley** [comment]
Get the latest git code.

Update the pip requirements.

```bash
git pull
pip install -U -r requirements.txt
```

**Comment by mxrch** [comment]
Don't forget the --upgrade when installing dependancies with pip, otherwise it won't update, just installing new packages. :)

**Comment by jevarlet** [comment]
Thank you both. This fixed the issue.

> pip install --upgrade -r requirements.txt
