### ISSUE TITLE
Chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by tpetry** [mxrch/GHunt#33]
* Python: 3.6
* Chrome Driver: 86.0.4240.22

```
[tobias@localhost GHunt]$ python3.6 check_and_gen.py
__Secure-3PSID => .....
APISID => ....
SAPISID => ....
HSID => ....

[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => ....
Traceback (most recent call last):
  File "check_and_gen.py", line 77, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.6/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127
```

**Comment by mxrch** [comment]
Hello @tpetry , crashes can happens, but this type of crash usually do not reappear when you retry. Is this crash permanent ?

**Comment by Bapt5** [comment]
@mxrch Yes this carsh is premanent

**Comment by mxrch** [comment]
@Bapt5 you are having a utf-8 error, no ? Can you create a new issue for that ?

**Comment by Bapt5** [comment]
@mxrch Oh yes excuse me But I thought that it's the same because @QuentinReyn has mentioned this issue in my issue.

**Comment by mxrch** [comment]
@Bapt5 no problem, I don't know why he did that..

**Comment by tpetry** [comment]
The problem is still persisting

**Comment by x0pa** [comment]
same issue here too

**Comment by mxrch** [comment]
@tpetry @x0pa can you tell me if it fix your issue ? https://stackoverflow.com/questions/49323099/webdriverexception-message-service-chromedriver-unexpectedly-exited-status-co

**Comment by mxrch** [comment]
Also, on what operating system are you ?

**Comment by tpetry** [comment]
The automatic chrome driver installation you added solved the problem

**Comment by barbel-thierry** [comment]
I just ran into the same issue, so if it can help someone:
you can actually drop the chromedriver at the root of GHunt (download it [here](https://sites.google.com/a/chromium.org/chromedriver/downloads))
