### ISSUE TITLE
Unsupported Protocol

### ISSUE THREAD

**Issue by Bapt5** [mxrch/GHunt#34]
![image](https://user-images.githubusercontent.com/63651713/95057770-e514d000-06f6-11eb-989f-5a1f90d7ecbb.png)
When I execute the file check_and_gen.py and I put the cookies values I have this error.

**Comment by mxrch** [comment]
Hello, @Bapt5  is this crash permanent ?

**Comment by Bapt5** [comment]
Yes I've try 10 time and it doesn't work every time

**Comment by mxrch** [comment]
@Bapt5  are you using a proxy or VPN ?

**Comment by Bapt5** [comment]
@mxrch Ok Thank you. You have right it was the proxy. But now I've this error. I think that it's about utf-8. But I don't understand why? 
<img width="618" alt="Capture" src="https://user-images.githubusercontent.com/63651713/95075694-efdc5e80-0710-11eb-9129-d17bc31c19e9.PNG">

**Comment by mxrch** [comment]
@Bapt5 can you create a new issue for that ? 😄

**Comment by QuentinReyn** [comment]
@mxrch same issue as https://github.com/mxrch/GHunt/issues/33

**Comment by mxrch** [comment]
> 
> 
> @mxrch same issue as #33

@QuentinReyn so please go at this issue, since this issue as nothing to do with.
I'll also ask you to answer the same question I asked to tpetry in #33 .
