### ISSUE TITLE
unexpected keyword argument 'print_first_line'

### ISSUE THREAD

**Issue by AlvinPix** [mxrch/GHunt#343]
![Captura de pantalla de 2022-05-22 23-17-51](https://user-images.githubusercontent.com/96206578/169736811-a63402f0-ac3c-4f49-8fe4-7161f9850fb7.png)

all dependencies are satisfied but the chrome driver does not load it

python3 -m install -r requirements.txt

**Comment by mxrch** [comment]
Effectively, the developers of webdriver-manager seems to have removed the "print_first_line" argument in this commit : https://github.com/SergeyPirogov/webdriver_manager/commit/bcf04561558a42b70f4e7da81b33b95857d15435#diff-ee644570c7a18cf38dd2750a1329930218da3e06619048bdf55c76057887d069L19
I don't know why, but I'll hardcode an older version in the requirements while I can understand more.
