### ISSUE TITLE
Error in check_and_gen.py

### ISSUE THREAD

**Issue by Chrisfranco01** [mxrch/GHunt#346]
error in check_and_gen.py

![Screenshot_2](https://user-images.githubusercontent.com/61951238/171882739-bde2ce70-4a0e-460d-8038-7302206931d8.png)

 - Windows 10 64bits
 - Python 3.10.4

**Comment by hackerkartel64** [comment]
i have this problem in kali too. Is anyone gonna provide a solution for us ??

**Comment by mxrch** [comment]
Duplicate of https://github.com/mxrch/GHunt/issues/304.

**Comment by hackerkartel64** [comment]
mxrch the best
