### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Franc-ctrl** [mxrch/GHunt#35]
Got this one:

Traceback (most recent call last):
  File "hunt.py", line 97, in <module>
    data = ytb.get_channels(client, name, cfg)
  File "/home/osint/GHunt/lib/youtube.py", line 64, in get_channels
    from_youtube = youtube_channel_search(client, query)
  File "/home/osint/GHunt/lib/youtube.py", line 15, in youtube_channel_search
    data = json.loads(source.split('window["ytInitialData"] = ')[1].split('window["ytInitialPlayerResponse"]')[0].split(';\n')[0])
IndexError: list index out of range

could you fix it?

**Comment by Franc-ctrl** [comment]
and also:

Traceback (most recent call last):
  File "hunt.py", line 101, in <module>
    confidence, channels = ytb.get_confidence(data, name, hash)
TypeError: cannot unpack non-iterable NoneType object

**Comment by mxrch** [comment]
Hello @Franc-ctrl , thanks for reporting this, I'll take a look.
It is not required but if you can send me the email you are trying with it would help the debug, I understand if you won't.

**Comment by PinkDev1** [comment]
Correct me if I'm wrong, but I think this is exactly what oxadam is trying to fix on PR #32

**Comment by mxrch** [comment]
@Franc-ctrl I pushed a fix for another issue but I think it will solve your issue too, can you confirm ? https://github.com/mxrch/GHunt/commit/910bcb2033dce5a78c76af8ae9c7cfbed46f1a9f

**Comment by mxrch** [comment]
No response since 2 days, I'm closing this issue.
@Franc-ctrl I let you re-opening this issue if needed.

**Comment by Franc-ctrl** [comment]
Works fine now!!! :D :D :D
