### ISSUE TITLE
[-] [modwall] I can't find the library geopy

### ISSUE THREAD

**Issue by TopicOffic** [mxrch/GHunt#354]
I was trying to run a simple search `python ghunt.py email@address.com` and got this error:

```
[-] [modwall] I can't find the library geopy, did you correctly installed the libraries specified in requirements.txt ? 😤

- Windows : py -m pip install --upgrade -r requirements.txt
- Unix : python3 -m pip install --upgrade -r requirements.txt
```

Tried to upgrade pip but the error persisted.

Python version: 3.10.4 [MSC v.1929 64 bit (AMD64)]

**Comment by Manuelq059** [comment]
Enter this code: 
python3 ghunt.py email email@address.com

**Comment by TopicOffic** [comment]
Thank you very much. "Solved"
