### ISSUE TITLE
Error in check_and_gen.py

### ISSUE THREAD

**Issue by carlosr301101** [mxrch/GHunt#357]
An error in check_and_gen.py

[-] I can't find the Client Auth Config API...

**System **
 - Kali linux
 - Python version 3.8.0

**Screenshots**

![issue git](https://user-images.githubusercontent.com/34899128/178841356-bc5f2840-a524-4343-b56d-0ea90cf55a68.png)

**Comment by SSSEAL-C** [comment]
I found a fix to this, seems to be not native gmail accounts, usually organisations. Sign out of all google accounts and sign in to the one you want to use **first** and then your other accounts, grab the cookies then execute the script again with the cookies.

**Comment by rhaby** [comment]
=good
