### ISSUE TITLE
is 'ghunt.py doc' not working anymore?

### ISSUE THREAD

**Issue by Donaid** [mxrch/GHunt#360]
**Describe the bug**
Everything is working except the document function. 
The email function working well, but the doc part gives an error.
I tried with several google document links, but the results are all the same.

Traceback (most recent call last):
  File "ghunt.py", line 40, in <module>
    doc_hunt(data)
  File "C:\Users\k\ghunt\modules\doc.py", line 78, in doc_hunt
    created_date = datetime.strptime(data["createdDate"], '%Y-%m-%dT%H:%M:%S.%fz')
KeyError: 'createdDate'

**Screenshots**

![Screenshot_9](https://user-images.githubusercontent.com/11995062/182962319-7e8ddaf1-1cd5-444a-a9e3-485404ba4b67.png)
![download](https://user-images.githubusercontent.com/11995062/182964541-548efa60-109e-467c-9f33-6f239a0c7999.jpg)

**Comment by 00-Python** [comment]
Any luck solving this? i have the same error.

**Comment by rwxhugo** [comment]
same error here as well.

**Comment by dbechrd** [comment]
This is the real error if you inspect the response:
```
{'error': {'errors': [{'domain': 'global', 'reason': 'required', 'message': 'Authentication token must be issued to a non-anonymous app.', 'locationType': 'header', 'location': 'authorization'}], 'code': 400, 'message': 'Authentication token must be issued to a non-anonymous app.'}}
```

**Comment by Huderon** [comment]
It's not a clean solution but if you follow along with [this](https://cloud.google.com/docs/authentication/api-keys) you can generate a new api key linked to a google cloud project, once you've got that you've just got to add google drive service to that project and it should work.

**Comment by haroldKryptus** [comment]
Same error here, didnt understand how to use a google project on ghunt

**Comment by Huderon** [comment]
> Same error here, didnt understand how to use a google project on ghunt

Once you've got the API key for the project go to the data file in ./resources and replace the "internal" key with the new API key
