### ISSUE TITLE
enhancement: contact picture?

### ISSUE THREAD

**Issue by nikaiw** [mxrch/GHunt#363]
The first call to https://people-pa.clients6.google.com/v2/people/lookup?key=<key> may return a contact picture url.
I suspect that contact picture is only used for hanghout and only non-default if you access it from an account which is a contact of the target.

However, I don't know if there are cases where it would be public nor I can judge the interest that it could present for the project.
A dirty and easy way to test it is to add the following snippet [line 57 of email.py](https://github.com/mxrch/GHunt/blob/00656c8b6cb13b023effb6842aa5881b88c54071/modules/email.py#L57)
```python    
try:
    contact_pic = (data['people'][next(iter(data['people']))]['photo'][0]['url'])
    print("[+] contact picture found ")
    print(f"=> {contact_pic}")
except:
    pass
```

**Comment by mxrch** [comment]
Hey,
I should remove the contact fetching since it can confuse GHunt users :/
It's only the people you added in your Google contacts, so it's not public data.
Your PR is good, but I don't know if that's useful, since it would show the profil pic you put yourself. 😄

**Comment by nikaiw** [comment]
Yes I don't know if that's interesting, but from an account (contact of the target) I could grab the contact picture of people who only had the defaut profle picture.

I'm confused myself since for some contact I'm sure it's not a pic I have setup myself. There must be a moment when google grabbed those from another source like Google+ profile maybe ?

**Comment by nikaiw** [comment]
closing the issue since I suspect it does no really bring anything interesting.
