### ISSUE TITLE
does not work after correct cookie and token generation

### ISSUE THREAD

**Issue by fabricarneval** [mxrch/GHunt#366]
I correctly generate cookies and tokens but it doesn't work

![Cattura](https://user-images.githubusercontent.com/114477693/192484170-542fe406-5210-4173-aa29-03a839a7efbe.PNG)

**Comment by tallona** [comment]
I'm seeing in  `get_authorization_source` that the call to hangouts is returning a 302 always as hangouts redirects to `https://mail.google.com/chat/u/0/`
