### ISSUE TITLE
Potential new scan?

### ISSUE THREAD

**Issue by SSSEAL-C** [mxrch/GHunt#369]
While editing my Google Play profile on Google, I noticed that this was an option which I disabled.
![image](https://user-images.githubusercontent.com/83465508/195257409-fb211e39-d8b8-496d-92e4-f0d8017aef6f.png)
Potentially a new thing to scan for?

**Comment by mxrch** [comment]
Hello, great finding, it might be already studied, reverse engineered and integrated in GHunt v2 🥷

**Comment by SSSEAL-C** [comment]
Ooooooh? Sneak peak :P
