### ISSUE TITLE
LSID COOKIE NOT FOUND

### ISSUE THREAD

**Issue by AaryanK3304** [mxrch/GHunt#376]
now how to find LSID cookie currently

**Comment by Micro0x00** [comment]
+1

**Comment by perturbatorx** [comment]
Google has changed the cookie structure and the LSID cookie is no longer "clickable" by using the old method by simply browsing to the "cookie folder" in Chrome' security & privacy etc. section. Also this is why the import cookie method 1+2 are failing. I originally got the tool running by using the Base64 import method. 

The whole structure pertaining to LSID cookie seems drastically changed on all platforms. 

I hope that there is a workaround as this is a great tool that is stable - unless someone has a solution I believe that awaiting a solution is the best option.

**Comment by dennixone** [comment]
some, it doesnt work anymore - > LSID Cookie is not existing

**Comment by mxrch** [comment]
Should be fixed in https://github.com/mxrch/GHunt/pull/384.
