### ISSUE TITLE
Problem with LSID cookie

### ISSUE THREAD

**Issue by mxrch** [mxrch/GHunt#379]
This issue is known, Google changed something, no need to spam every issue / the discord / my PMs.
I'm currently busy, instead of searching a fix, I'll release a rushed version of GHunt v2 (and GHunt Companion v2) in the next days.

Be patient, or contribute by fixing the problem yourself ! Would be cool to contribute.

**Comment by nobita303** [comment]
@mxrch Bro when GHunt v2 will release?
