### ISSUE TITLE
UnicodeDecodeError UTF-8

### ISSUE THREAD

**Issue by Bapt5** [mxrch/GHunt#38]
When I put the cookies I get the Google Docs Token but then there is an error. 
<img width="618" alt="Capture" src="https://user-images.githubusercontent.com/63651713/95076781-b147a380-0712-11eb-9ddf-cd09d6453333.PNG">

**Comment by mxrch** [comment]
Hello @Bapt5 , have you modified the script to include a proxy ?

**Comment by Bapt5** [comment]
Hi @mxrch No I've just change my connection to make that there is no proxy

**Comment by rexdivakar** [comment]
I can fix it @mxrch  shall I ??

**Comment by mxrch** [comment]
> I can fix it @mxrch  shall I ??

Hello, yes you can do a pull request !

**Comment by Bapt5** [comment]
@rexdivakar Do you made the pull request ??

**Comment by Bapt5** [comment]
@mxrch The problem is still persisting. Can someone help me please?

**Comment by rexdivakar** [comment]
I'm looking into it give me sometime will fix it soon

**Comment by Bapt5** [comment]
Okay Thank you very much @rexdivakar

**Comment by rexdivakar** [comment]
May i know the details ??
__Secure-3PSID => as.fllas
APISID => af
SAPISID => af
HSID => af

**Comment by Bapt5** [comment]
What do you want to know?

**Comment by mxrch** [comment]
@Bapt5 can you do `python -c "import _socket;print(_socket.gethostbyaddr('www.google.com'))"` and tell me what it does ?
Just to know if you'll have the same error.
Reference : https://github.com/openwrt/packages/issues/1311

**Comment by Bapt5** [comment]
@mxrch No I have not the same error I receive this text. `('par10s28-in-f4.1e100.net', ['par10s28-in-f100.1e100.net'], ['216.58.204.100'])`

**Comment by Bapt5** [comment]
@rexdivakar Has you found a solution?
