### ISSUE TITLE
is_email_google_account func invalid，api program？

### ISSUE THREAD

**Issue by xcircle007** [mxrch/GHunt#382]
is_email_google_account {'error': {'code': 403, 'message': 'Internal People API has not been used in project 1021803392181 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people-pa.googleapis.com/overview?project=1021803392181 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/people-pa.googleapis.com/overview?project=1021803392181'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/1021803392181', 'service': 'people-pa.googleapis.com'}}]}}

**Comment by xasser** [comment]
same issue

**Comment by mxrch** [comment]
same issue plz fix it

**Comment by xcircle007** [comment]
what, which issue, i didn't see。。。

**Comment by meonl** [comment]
same issuess ddoooo fix it fast

**Comment by i-decrypt** [comment]
same issue here

**Comment by pcortizona** [comment]
> same issue plz fix it

WTF! what do you mean fix it?

**Comment by xcircle007** [comment]
I found another way! Information such as user name and avatar can be successfully obtained. I'm doing some research

**Comment by pcortizona** [comment]
> 

I mean, if any one of us needs to fix some feature, spaming the hell out of the author  is not conducive  to contributions.

**Comment by mxrch** [comment]
Should be fixed in https://github.com/mxrch/GHunt/pull/384, thanks @ahmadhany !
