### ISSUE TITLE
Feature Request: Export to file, (JSON, TXT) formats.

### ISSUE THREAD

**Issue by SSSEAL-C** [mxrch/GHunt#387]
Hello, as title says I'd love if we could export the results to JSON specifically, but other formats are also appriciated. Is this possible in either this GHunt or the ominously eluded to GHunt 2?

**Comment by mxrch** [comment]
Hi ! It's already functional in GHunt v2, and it should come tomorrow or this weekend. 😄

**Comment by SSSEAL-C** [comment]
OH HELL YEA

**Comment by mxrch** [comment]
@SSSEAL-C it is out 👀
