### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yazarneon** [mxrch/GHunt#4]
I installed reqs. but when I run "python3 hunt.py mymail@gmail.com" I got below error.

python3: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

**Comment by mxrch** [comment]
Hello, I don't think it's related to GHunt but a missing library with your installation of Python, maybe try to reinstall Python 3.
