### ISSUE TITLE
ghunt.errors.GHuntKnowledgeError: The gmaps type "atm" has not been found in GHunt's knowledge.

### ISSUE THREAD

**Issue by diehard88** [mxrch/GHunt#400]
PYTHON 3.10
LINUX MINT

![ghunt gmaps error](https://user-images.githubusercontent.com/25366502/206321851-4e673247-dcc1-4a42-ad4d-358793cb7f08.png)

**Comment by mxrch** [comment]
Nice, I'll add it to GHunt's knowledge

**Comment by mxrch** [comment]
There are really people leaving reviews on ATMs :')

**Comment by diehard88** [comment]
> 

probably reviewing bitcoin atm's

**Comment by diehard88** [comment]
@mxrch I believe it's for bitcoin ATMs...

**Comment by mxrch** [comment]
@diehard88 should be fixed in https://github.com/mxrch/GHunt/commit/71144a099af55098c44f7f6a44c2affebbcb6420, can you try doing pipx uninstall ghunt; pipx install git+https://github.com/mxrch/ghunt@71144a099af55098c44f7f6a44c2affebbcb6420, retry and tell me if the problem is resolved ?

**Comment by diehard88** [comment]
> @diehard88 should be fixed in [71144a0](https://github.com/mxrch/GHunt/commit/71144a099af55098c44f7f6a44c2affebbcb6420), can you try doing `pipx uninstall ghunt; pipx install git+https://github.com/mxrch/ghunt@71144a099af55098c44f7f6a44c2affebbcb6420`, retry and tell me if the problem is resolved ?

SOLVED!

**Comment by diehard88** [comment]
thank you!
