### ISSUE TITLE
How to use with php ?

### ISSUE THREAD

**Issue by vijay399** [mxrch/GHunt#41]
It is working Charm with Python Command on terminal but how to use it with php I tried with Execute Commands but it didn't work. Please Help me to install with webpage

**Comment by mxrch** [comment]
![image](https://user-images.githubusercontent.com/17338428/95115839-647dc000-0746-11eb-9343-02764f4ebc11.png)

PHP is not intended to work with Python.

**Comment by Suleman-Elahi** [comment]
You can setup this on the server and run it with PHP's `shell_exec` and then parse the output.

**Comment by vijay399** [comment]
Using this line getting Blank Output

**Comment by Suleman-Elahi** [comment]
Looks like you are noob, so I am sorry I can't help further.
