### ISSUE TITLE
Is it possible to get information from any of the following link formats?

### ISSUE THREAD

**Issue by sealldeveloper** [mxrch/GHunt#413]
Potentially email, Gaia ID to utilize to get email, anything possible from these links?

https://photos.app.goo.gl/xxXxxXX1x23xxx4x5
https://docs.google.com/forms/d/e/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/viewform

Just wondering as the `drive` option doesn't accept any of the values as valid files, so potentially new options or just not possible?

Thanks, -seal

**Comment by sealldeveloper** [comment]
Any update on this?

**Comment by mxrch** [comment]
Hi, Google Forms and Google Photos does not permit to extract the same information as other Drive objects.
