### ISSUE TITLE
Problem witch LSID cookie and ghunt companion not working

### ISSUE THREAD

**Issue by haszimoto2** [mxrch/GHunt#419]
After update GH2  i cant synchronize ghunt companion and find LSID cookie

Any idea how to fix ?

**Comment by sealldeveloper** [comment]
Make sure you have the updated version of the extension to sync.

**Comment by haszimoto2** [comment]
which exactly? sorry im not programmer.

**Comment by sealldeveloper** [comment]
If you are trying to sync GHunt with your Google Account, do you have the latest version of the browser extension?

Mozilla Firefox: https://addons.mozilla.org/en-US/firefox/addon/ghunt-companion/
Chrome/Chromium: https://chrome.google.com/webstore/detail/ghunt-companion/dpdcofblfbmmnikcbmmiakkclocadjab

**Comment by mxrch** [comment]
Update GHunt and the GHunt Companion to have the latest version.
