### ISSUE TITLE
trio.BrokenResourceError: socket connection broken: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by diehard88** [mxrch/GHunt#421]
occasionally I'm getting the error shown in screenshot.

the same query is succesfully completed upon resubmission.

perhaps a short link failure?

raise trio DA DA DA?

:)

![Screenshot_20230205-203252_Termux](https://user-images.githubusercontent.com/25366502/216863232-d0c343c3-627d-4dc8-a08c-a772f16baa9f.jpg)

**Comment by mxrch** [comment]
Surely a client-side problem, an instable connection, VPN, proxy, public wifi, idk.
