### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'resources/data.txt'

### ISSUE THREAD

**Issue by belveruski** [mxrch/GHunt#44]
After this command `sudo docker run -v $(pwd)/resources:/usr/src/app/resources -ti ghunt check_and_gen.py` i got this error:

```bash
__Secure-3PSID => ******************************************
APISID => ******************************************
SAPISID => ******************************************
HSID => ******************************************

[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => *****************************************
Authorization Token => *****************************************
Hangouts Token => ********************************************
Traceback (most recent call last):
  File "check_and_gen.py", line 96, in <module>
    with open(cfg['data_path'], 'w') as f:
PermissionError: [Errno 13] Permission denied: 'resources/data.txt'
```

**Comment by mxrch** [comment]
@outime can you take a look at this ?

**Comment by 0xadam** [comment]
I get the same issue with the current master. My guess would be it's because the docker container is running as the "app" user, while the resources folders will be owned by whoever cloned it and have 755 permissions, meaning the container isn't able to write the data.txt there.

**Comment by outime** [comment]
I can provide a patch in the evening.

ti 6. lokak. 2020 klo 1.12 0xadam <notifications@github.com> kirjoitti:

**Comment by 0xadam** [comment]
Take a look at https://github.com/mxrch/GHunt/pull/46 as I think that should fix it.

**Comment by outime** [comment]
@0xadam it'd be nice to provide a way for Windows users as well. The README was already falling short because it used `pwd` so it's perhaps a good moment to provide a better example.

**Comment by 0xadam** [comment]
Ahh I see. Looks like under Windows the SMB protocol is used for volume mounts so permissions issues like this may not be a problem. But if they are I'm not how much can be done to easily fix them. Hopefully there is a way to get things working under it... Maybe the patch above but without passing the extra build args on Windows?

**Comment by baimard** [comment]
I have solved that problem by 

`docker run -v $(pwd)/resources:/usr/src/app/resources -u root -ti ghunt check_and_gen.py`
