### ISSUE TITLE
cookies invalid how do i validate therm

### ISSUE THREAD

**Issue by MangoWater69** [mxrch/GHunt#448]
Seems like the cookies are invalid. Exiting...
on python pycharm

**Comment by Rat-Tribal** [comment]
Same issue here, except im getting "cookies are invalid, try regenerating them".

**Comment by RiteshSec** [comment]
Same here. Even though I have tried entering cookies multiple times using all the 3 methods still getting the same error. It worked fine until 2 days back and suddenly got the issue. 

<img width="785" alt="image" src="https://github.com/mxrch/GHunt/assets/110530131/924ca823-abf6-4741-85dd-4242cfe6bf13">

**Comment by mxrch** [comment]
Can't reproduce :/

**Comment by Navitas28** [comment]
![Screenshot 2023-08-17 at 20 00 01](https://github.com/mxrch/GHunt/assets/8795442/3ac993a4-c014-4e89-8760-c461c0234325)


Same issue here tried both the ways

**Comment by dpanic** [comment]
Same here

**Comment by Theblood** [comment]
Same here :/  @mxrch

**Comment by mxrch** [comment]
There are two same issues, please move on this one : https://github.com/mxrch/GHunt/issues/456

**Comment by blackbla1** [comment]
> There are two same issues, please move on this one : #456

Are you planning to fix ghunt_companion?
