### ISSUE TITLE
Module Missing lib.ghunt

### ISSUE THREAD

**Issue by Marcker100** [mxrch/GHunt#477]
**Describe the bug**
error when calling sudo python3 check_and_gen.py

Traceback (most recent call last):
  File "/home/student/SocialPwned/lib/GHunt/check_and_gen.py", line 13, in <module>
    from lib.GHunt import config
ModuleNotFoundError: No module named 'lib.GHunt'

**System:**
 - OS Ubuntu 22.04.1 LTS
 - Python version 3.10

**Comment by mxrch** [comment]
It's related to an other project that is using GHunt v1, which is not supported anymore.
