### ISSUE TITLE
Ghunt login issue

### ISSUE THREAD

**Issue by Suzy1992** [mxrch/GHunt#479]
I am not able to login into Ghunt, Everytime I try it says cookies invalid. I have tried on multiple systems and only one account is logged in on Firefox. Can someone help me on this..
@mxrch @ghunt @esidate

GHunt is listening on port 60067...
[+] Received cookies !

[-] Seems like the cookies are invalid, try regenerating them.

**Comment by esidate** [comment]
Hi @Suzy1992 try logging out your Gmail account and log in again

**Comment by w0dxDev** [comment]
Fok

**Comment by shion1305** [comment]
https://github.com/mxrch/GHunt/issues/476#issuecomment-1885723506

**Comment by mxrch** [comment]
Effectively, duplicate of https://github.com/mxrch/GHunt/issues/476, thanks @shion1305.
