### ISSUE TITLE
Unable to init ghunt login (python 3.9 error)

### ISSUE THREAD

**Issue by elcitrovmtgrande** [mxrch/GHunt#483]
<img width="968" alt="Screenshot 2024-01-19 at 13 44 09" src="https://github.com/mxrch/GHunt/assets/39875237/347c4dcf-5b12-4af9-8a45-80a528a1b380">
**Describe the bug**
After following the procedure, when running ghunt login, python throws errors on Mac OS.

**To Reproduce**
1. Follow the installation procedure
2. Type `ghunt login`
3. See the bug

**Expected behavior**
Should be launched successfully.

**Screenshots**
See attached.

**System (please complete the following information):**
 - OS : Mac OS Sonoma 14.1
 - Python version : 3.19

**Comment by mxrch** [comment]
Because the Readme says you have to use Python 3.10+.
