### ISSUE TITLE
Parsing first name and last name from Google Account by email doesn't work

### ISSUE THREAD

**Issue by shulgadanilazxc** [mxrch/GHunt#508]
**Describe the bug**
When I try to get first name and last name of the account which I used to generate creds.m everything works fine, but when I try to retreive data of another account - the result is empty

**To Reproduce**
1. Run command ghunt email any email apart of that which has been used to generate creds.m --json user_data.json

**Expected behavior**
Retreive first name and last name from Google Account

**System (please complete the following information):**
 - OS Windows 10/Linux Ubuntu 22.04.2
 - Python version 3.10.12/3.11.0

**Comment by MeHowHere** [comment]
https://github.com/Epieos/GHunt/pull/1

i think it will help u
