### ISSUE TITLE
Geolocate function does not work.

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [mxrch/GHunt#524]
**Describe the bug**
When running `ghunt geolocate (bssid here)` it always returns the following error: "Location not found.".
I have tried with several other bssids of networks in my area and they all return the same error.

**To Reproduce**
1. Retrieve bssid from nearby and my own WiFi networks
2. Run Ghunt geolocate (bssid here)
3. Expect it to return a location or something
4. Does not work

**Expected behavior**
It should return the location of the bssid.

**Screenshots**
![image](https://github.com/user-attachments/assets/79ada6de-5327-4578-9b9d-806e83a73f1f)

**System (please complete the following information):**
 - Windows 10 x64 Pro [Microsoft Windows [Version 10.0.19045.4780]]
 - Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32

**Additional context**
I have tried it with multiple BSSID's including my own and seen the same results.
Either this function has been patched from Google's API, or I am inputting the data wrong.
Since nobody else has complained about this yet, I may be the first.

**Comment by mxrch** [comment]
Hey ! Sorry, it can happens.
This API needs at least two BSSID to work, and the one I hardcoded seemed to be the best as it gave results for a lot of other BSSIDs.
Let me know if you find a better one, and I'll be happy to use it.

**Comment by mxrch** [comment]
But you're right, even the example don't work anymore.
The endpoint seems to still be working, but I don't have working examples anymore.
