### ISSUE TITLE
pipx installation symlink

### ISSUE THREAD

**Issue by diehard88** [mxrch/GHunt#528]
root@localhost:~# pipx install ghunt
⚠️  File exists at /root/.local/bin/ghunt and points to /root/.local/bin/ghunt, not /root/.local/share/pipx/venvs/ghunt/bin/ghunt.
    Not modifying.
  installed package ghunt 2.2.0, installed using Python 3.10.12
  These apps are now globally available
    - ghunt (symlink missing or pointing to unexpected location)
done! ✨ 🌟 ✨

________________________________

root@localhost:~# pipx list
venvs are in /root/.local/share/pipx/venvs
apps are exposed on your $PATH at /root/.local/bin
manual pages are exposed at /root/.local/share/man
   package ghunt 2.2.0, installed using Python 3.10.12
    - ghunt (symlink missing or pointing to unexpected location)
    -

**Comment by mxrch** [comment]
Sorry I can't understand the issue, and if that's a symlink issue, it's related to your system, but not to GHunt.
Look at on the side of pipx / bash
Reopen this issue if you think my point is wrong
