### ISSUE TITLE
Version for 'google-chrome-stable' was not found

### ISSUE THREAD

**Issue by JuliaCao** [mxrch/GHunt#58]
I got this error when running docker build, had to manually update it to the latest google chrome version in Dockerfile for it to work.

**Comment by mandadimuralidharreddy** [comment]
change chrome version in docker to below
**ENV CHROME_VERSION 86.0.4240.75-1**

**Comment by JuliaCao** [comment]
I did.

My point is this was not mentioned in README. We might want to consider adding it or find a better way to automate?

**Comment by Demmonius** [comment]
May the dockerfile be update? It doesn't work if you don't change this version. Thanks :D

**Comment by tpetry** [comment]
@outime You hardcoded the chrome version in the docker file which is a bad idea as it has been already superseded with a new version. Is it possible to load the newest version and load a matching chrome driver?

**Comment by outime** [comment]
@tpetry well, I don't think it's a bad idea. It makes sense to stick to a known version that works than using the latest one and then having to figure out why it works for some users and why it doesn't for others. It's unfortunate that they removed the package for the previous version so quickly. I see two solutions:

- Either we do what you suggest, which could be achieved with a script run on docker build which would get the latest versions - being fully aware that we lose one of the benefits of using Docker which is portability, and that this will create other problems.
- Or we just include the binaries in the project and add them on Docker build (this is my preference if there are no legal issues for the aforementioned reasons).

Let's see if any of tha maintainers can chime in.

**Comment by tpetry** [comment]
Because of #33 i am unable to test it correctly.

I modified the Dockerfile to not use the apt repository (because the files are replaced every few days) but to download them (and they seem to be available there much longer). Is https://github.com/tpetry/GHunt/blob/master/Dockerfile working for someone? If it is working i start a pull request.

**Comment by outime** [comment]
@tpetry at least it builds for me. One thing though, why `gdebi` and not use the built-in `dpkg -i ...`? Also a minor thing an extra space in the `curl`.

**Comment by tpetry** [comment]
`dpkg -i` is not resolving the dependencies by the `deb`, you have to install them before installation. And who knows which dependencies chrome will need today and tomorrow. `gdebi` on the other hand resolves the dependencies and loads them. I will fix the curl.

Yeah i can test whether it's building too, but running does not work for me - no matter if dockerized or not. Can anyone verify that the new docker image is working correctly?

```
# replace Dockerfile, then execute the following steps
docker build --tag tpetry-ghunt .
docker run -it ghunt check_and_gen.py
```

**Comment by outime** [comment]
It doesn't:

```
[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => xxx
Traceback (most recent call last):
  File "check_and_gen.py", line 73, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127
```

But then it might be related to the build process. I see some errors not seen before:

```
...
Processing triggers for systemd (241-7~deb10u4) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
E: No packages found
Reading package lists...
Building dependency tree...
...
Requires the installation of the following packages: fonts-liberation libappindicator3-1 libasound2 libasound2-data libdbusmenu-glib4 libdbusmenu-gtk3-4 libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2 libelf1 libfile-desktopentry-perl libfile-mimeinfo-perl libfontenc1 libgbm1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libice6 libindicator3-7 libio-stringy-perl libllvm7 libnet-dbus-perl libnspr4 libnss3 libpciaccess0 libsensors-config libsensors5 libsm6 libtext-iconv-perl libtie-ixhash-perl libwayland-server0 libx11-protocol-perl libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shape0 libxcb-sync1 libxml-twig-perl libxml-xpathengine-perl libxmu6 libxmuu1 libxpm4 libxshmfence1 libxt6 libxv1 libxxf86dga1 libxxf86vm1 wget x11-utils x11-xserver-utils xdg-utils

The web browser from Google
 Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
Do you want to install the software package? [y/N]:/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
```

**Comment by tpetry** [comment]
Does it work for you without docker?

**Comment by JuliaCao** [comment]
> Does it work for you without docker? Because this is exactly the problem of #33 which is happening without docker too...

I'm not sure if this is the same as your error: ```Message: Service ./chromedriver unexpectedly exited. Status code was: 127```

**Comment by belveruski** [comment]
Same error:

```bash
E: Version '85.0.4183.121-1' for 'google-chrome-stable' was not found
The command '/bin/sh -c groupadd -g ${GID} -r app && adduser --system --home /home/app --ingroup app --uid ${UID} app &&     chown -R app:app /usr/src/app &&     apt-get update &&     apt-get install -y curl unzip gnupg &&     curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list &&     apt-get update &&     apt-get install -y google-chrome-stable=${CHROME_VERSION} &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by mxrch** [comment]
Hello guys, you may be removing the hardcoded version of Google Chrome in the Dockerfile since the last push includes the auto-install of chromedriver, so not need anymore to be sure to have the same version for Google Chrome and chromedriver.
Since I'm not a Docker user I let you doing a pull request to fix that !

**Comment by JuliaCao** [comment]
> I modified the Dockerfile to not use the apt repository (because the files are replaced every few days) but to download them (as they seem to be available there much longer).
> 
> Is [https://github.com/tpetry/GHunt/blob/master/Dockerfile](https://github.com/tpetry/GHunt/blob/master/Dockerfile?rgh-link-date=2020-10-07T10%3A01%3A24Z) working for someone? Because of #33 i am unable to test it correctly. If it is working i start a pull request.

This worked for me. I was able to build the image and run the python scripts

**Comment by outime** [comment]
@mxrch alright let me take a look, thanks for the heads up.

**Comment by outime** [comment]
I opened a PR #71 that seems to fix everything. I could use both scripts and worked very well.

**Comment by mxrch** [comment]
Thanks to @outime the I merged is fix.
@JuliaCao does it works now ?

**Comment by JuliaCao** [comment]
> Thanks to @outime I merged his fix.
> @JuliaCao does it work now ?

Looks good to me. Thank you!
