### ISSUE TITLE
Forgot to install the Chrome driver, had to retype all the cookies values 

### ISSUE THREAD

**Issue by vallas** [mxrch/GHunt#6]

**Comment by mxrch** [comment]
Yeah maybe I'll do a thing for this but it's not my priority right now.

**Comment by mxrch** [comment]
Finally it was just a minor change https://github.com/mxrch/GHunt/commit/319c65ea7a22b2382cc0f7a151f45c94c56c97d9 :)

**Comment by sheddup** [comment]
give the option to load cookies from a file
