### ISSUE TITLE
AttributeError: 'JpegImageFile' object has no attribute 'getexif'

### ISSUE THREAD

**Issue by com0t** [mxrch/GHunt#60]
i was install requirements.txt

**Comment by PinkDev1** [comment]
Post the full error message, the command you ran, and your python version; Otherwise we can't help you

Due to vagueness, this might just be a duplicate of #54

**Comment by mxrch** [comment]
So you got an AttributeError when installing the requirements.txt ? 🤔 
Please help us understand by doing what PinkDev1 said.
