### ISSUE TITLE
chromedriver 

### ISSUE THREAD

**Issue by MZIntelligence** [mxrch/GHunt#61]
Directory 
/home/user/GHunt

Installed requirements and dependencies.
Operating System: Linux Ubuntu OS Subsystem --> Windows 10

Error:!
The chromedriver is missing.
Please put it in the GHunt directory.

![image](https://user-images.githubusercontent.com/61881919/95346267-44065080-0881-11eb-8088-cd9b0ca61ebf.png)

Any tips to make it work with sublinux? I am guessing this could either be an issue with the headless browser or something else. Tried adding the tokens manually to the to data.txt file I create manually as it doesnt generate but need the right format to test. 

Thoughts?

**Comment by mxrch** [comment]
Hello @MZIntelligence , can you retest with the latest push ? We added the auto-install of chromedriver.

**Comment by MZIntelligence** [comment]
Hey @mxrch tested it real quick and it got me pass the chromedriver but now I seem to have issues with the headleas chrome.  
![image](https://user-images.githubusercontent.com/61881919/95396831-6cb13900-08c7-11eb-82b3-70808fe7a6ca.png)

I did get it to work on my CentOS VM. So this seems to be one of those headaches when it comes to Sublinux on Windows. I'd be happy to keep on troubleshooting this and see if I can make it work there.

**Comment by mxrch** [comment]
Hm weird, people who did the WSL support doesn't had this problem.. @christianboyle an idea ?

**Comment by christianboyle** [comment]
No, I never ran into this error. Aside from installing `chromedriver.exe` things should be working if you are running latest versions of everything and WSL 1.

**Comment by christianboyle** [comment]
Just confirmed everything is working with the following:

1. `git clone git@github.com:mxrch/GHunt.git`
2. `cd GHunt`
3. `python3 -m pip install -r requirements.txt`
4. `python3 check_and_gen.py`
5. (it doesn't find chromedriver.exe, so it downloads and installs automatically)
6. Enter auth tokens
7. `python3 hunt.py larrypage@gmail.com`

**Comment by mxrch** [comment]
I'm closing this issue, feel free to reopening it if needed.
