### ISSUE TITLE
groupadd: GID '20' already exists

### ISSUE THREAD

**Issue by kapik** [mxrch/GHunt#62]
Hey! 

I'm running the docker build command on Mac.
I have this error: 
```
Step 7/13 : RUN groupadd -g ${GID} -r app && adduser --system --home /home/app --ingroup app --uid ${UID} app &&     chown -R app:app /usr/src/app &&     apt-get update &&     apt-get install -y curl unzip gnupg &&     curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list &&     apt-get update &&     apt-get install -y google-chrome-stable=${CHROME_VERSION} &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 11057b3da1f4
groupadd: GID '20' already exists
The command '/bin/sh -c groupadd -g ${GID} -r app && adduser --system --home /home/app --ingroup app --uid ${UID} app &&     chown -R app:app /usr/src/app &&     apt-get update &&     apt-get install -y curl unzip gnupg &&     curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list &&     apt-get update &&     apt-get install -y google-chrome-stable=${CHROME_VERSION} &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 4
```

FYI: the USER variable is set

**Comment by mxrch** [comment]
I am letting this issue to the Dockerize PR people 😄

**Comment by tpetry** [comment]
@mxrch This bug is solved in the newest `Dockerfile`

**Comment by PiotrBandurski** [comment]
@tpetry Unfortunately problem still occurs
```
groupadd: GID '20' already exists
The command '/bin/sh -c groupadd -g ${GID} -r app && adduser --system --home /home/app --ingroup app --uid ${UID} app &&     chown -R app:app /usr/src/app &&     apt-get update &&     apt-get install -y curl unzip gnupg &&     curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list &&     apt-get update &&     apt-get install -y google-chrome-stable=${CHROME_VERSION} &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 4
```

**Comment by tpetry** [comment]
@PiotrBandurski Update the source code. The `Dockerfile` has been changed to use `gid/uid = 1000`

**Comment by PiotrBandurski** [comment]
@tpetry I'm using latest code from master

**Comment by PiotrBandurski** [comment]
@tpetry Oh sorry I had some cache, now its working

**Comment by enderax** [comment]
Hi,
First time, I cloned the repo today but the same error still occurs

**Comment by gjgd** [comment]
I also got the error with the current code on master (https://github.com/mxrch/GHunt/tree/5b3756738b2b3479b0d6b5c7e8f3042655d1a133)

**Comment by wovalle** [comment]
I also got the error and I (kind) of fixed it by editing the -o as the first option of the `groupadd` command in the Dockerfile:

`groupadd -g ${GID} -r app`

Don't know enough about linux tools to know if this is a bad practice though, I assume the error was because I'm in a mac

**Comment by gjgd** [comment]
That worked for me as well

**Comment by omsrisagar** [comment]
This worked for me as well, thank you @wovalle

**Comment by seyanaracore** [comment]
> I also got the error and I (kind) of fixed it by editing the -o as the first option of the `groupadd` command in the Dockerfile:
> 
> `groupadd -o -g ${GID} -r app`
> 
> Don't know enough about linux tools to know if this is a bad practice though, I assume the error was because I'm in a mac

You are god
