### ISSUE TITLE
Cannot find Chrome binary

### ISSUE THREAD

**Issue by lalarobin** [mxrch/GHunt#65]
[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...                                                                                                                                                                  Google Docs Token => AC4w5VhkP2mR4i2Ec4Wda-41iFSZ2W-zZQ:1602119868718                                                   Traceback (most recent call last):                                                                                        File ".\check_and_gen.py", line 75, in <module>                                                                           driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)           File "C:\Users\whatever\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\seleniumwire\webdriver\browser.py", line 86, in __init__                                           super().__init__(*args, **kwargs)                                                                                     File "C:\Users\whatever\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__                                      RemoteWebDriver.__init__(                                                                                             File "C:\Users\whatever\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__                                     self.start_session(capabilities, browser_profile)                                                                     File "C:\Users\whatever\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session                                response = self.execute(Command.NEW_SESSION, parameters)                                                              File "C:\Users\whatever\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute                                      self.error_handler.check_response(response)                                                                           File "C:\Users\whatever\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response                            raise exception_class(message, screen, stacktrace)                                                                  selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by mxrch** [comment]
Hello, have you Google Chrome installed ?

**Comment by lalarobin** [comment]
Yes, it's my primary browser

**Comment by mxrch** [comment]
It means you do not have Google Chrome installed in standard locations.. can you try reinstalling it, or try this : https://groups.google.com/d/msg/chromedriver-users/EURx0cP5olg/aMsS5fm4DgAJ ?
You can also search for the error online there is a lot of topics.
