### ISSUE TITLE
every time i feel up the values of the cookies it says: Seems like the cookies are invalid, try regenerating them.  whats the problem here

### ISSUE THREAD

**Issue by presmedia002** [mxrch/GHunt#66]
every time i feel up the values of the cookies it says: Seems like the cookies are invalid, try regenerating them.

whats the problem here

**Comment by presmedia002** [comment]
made sure to not include the quotes when pasting them.

**Comment by mxrch** [comment]
Try disconnect and relogin in your Google Account and take the cookies with the right names, and try to login to Hangouts and Google Docs just to be sure you don't have a popup, warning or anything else, because it uses Hangouts and Google Docs to check for the cookies.

**Comment by alfonsostg** [comment]
Exact same issue for me.

OS: MacOS catalina 10.15.4

Manual (not docker) installation, clean G account re-logged in, cookies taken from Chrome.

**Comment by mxrch** [comment]
@presmedia002 @alfonsostg does it works with the last updates ?

**Comment by alfonsostg** [comment]
@mxrch `[+] The cookies seems valid !`!

But after it fails in opening browser with:

```sh
Google Docs Token => XXXXXXXXXXXXXXXXXXXXXXXX:NNNNNNNNNNN
Traceback (most recent call last):
  File "check_and_gen.py", line 159, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 70, in get_hangouts_tokens
    chrome_options=chrome_options
  File "/Users/me/opt/anaconda3/lib/python3.7/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/me/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/me/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/me/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 255, in start_session
    self.session_id = response['sessionId']
TypeError: 'NoneType' object is not subscriptable
```

From the [documentation](https://github.com/mxrch/GHunt#usage) I wasn't expecting it to open a browser, just to generate the tokens.

Why is it opening a browser? Just in case, my chrome version is `Version 86.0.4240.111 (Official Build) (x86_64)
`

**Comment by mxrch** [comment]
Is it opening an automated browser to execute the obfuscated Javascript.
So I guess you talk about the Chrome browser version, now what's your chromedriver version ? Either it auto installed a folder in the GHunt directory like a folder named "86" either you manually downloaded the chromedriver in the GHunt directory.

**Comment by alfonsostg** [comment]
Hey.

FYI: `ChromeDriver 86.0.4240.22`

If I just:

```sh
Enter these browser cookies found at accounts.google.com :
__Secure-3PSID => 
APISID => 
SAPISID => 
HSID => 

[+] The cookies seems valid !
Generating the Google Docs and Hangouts token...

Google Docs Token => XXXX:NNNN
Error making request page...
Traceback (most recent call last):
  File "/Users/me/opt/anaconda3/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
(...)
```

But If I:

```sh
./chromedriver&
[1] 12214
Starting ChromeDriver 86.0.4240.22
(...)
(base) ➜  GHunt git:(master) ✗ python check_and_gen.py
[+] Detected stored cookies, checking it

[+] The cookies seems valid !

Do you want to enter new browser cookies from accounts.google.com ? (Y/n) n
Do you want to generate new Google Docs and Hangouts tokens ? (Y/n) y
Generating the Google Docs and Hangouts token...

Google Docs Token => 
Authorization Token =>
Hangouts Token =>
```

And I can correctly use GHunt!

**Comment by pmgcrypto** [comment]
Might I recommend using something to grab the cookies programmatically from Chrome? 
https://github.com/n8henrie/pycookiecheat
I could send over a pull request sometime this weekend.
