### ISSUE TITLE
Google Photos public photos found but cant see them when visiting URL

### ISSUE THREAD

**Issue by pawisoon** [mxrch/GHunt#67]
I got the following output but when I go to the url it shows 404 error.

```
Google Photos : https://get.google.com/albumarchive/XXXXXXXXXXXXXXX
=> 5 albums, 5 photos      
```  

```
404. That’s an error.

The requested URL was not found on this server. That’s all we know.
```

**Comment by mxrch** [comment]
Yeah I didn't want to include the URL used for the bypass but I think I should to avoid issues like this.

**Comment by mxrch** [comment]
I edited it in https://github.com/mxrch/GHunt/commit/fed329133c1b0ab1e34cdf3d82816af503265372 !
