### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by noobkiddie** [mxrch/GHunt#69]
i see this error
![cookie](https://user-images.githubusercontent.com/72414695/95442873-e5e17800-0929-11eb-9f59-a066e9c53399.png)

**Comment by outime** [comment]
@noobkiddie I assume you use Docker, what OS? Also, can you try to update to the latest `master` and build the image again? There were changes that could fix your problem.

**Comment by noobkiddie** [comment]
I use kali linux OS. ok fine i will update both of my systems and tool.

**Comment by mxrch** [comment]
@noobkiddie I'm sure you put your script in something like /usr/share or /opt, try to put it in your home directory or your desktop.
You can't write a file in a directory where you doesn't have rights.

**Comment by noobkiddie** [comment]
thanks brother. it worked nice tool and i have some doubt on. 

![ckie](https://user-images.githubusercontent.com/72414695/95614073-f54ce800-0a33-11eb-9549-1f2899a1b079.png)
