### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by outime** [mxrch/GHunt#7]
I'll submit a PR soon so that a Docker image can be built easily and you can then decide if you want to merge it, build a GitHub action to automatically build it and upload it to Docker Hub, etc so it gets much easier to setup and use.

**Comment by mxrch** [comment]
Thank you, appreciate it !
Not all heroes wear capes 🦸

**Comment by tpetry** [comment]
Github has now a free container registry which a github action could push to. So source and docker would be on the same platform ;)
