### ISSUE TITLE
Reverse search?

### ISSUE THREAD

**Issue by 5l1v3r1** [mxrch/GHunt#80]
Thank you for the great tool. It works flawlessly as it is claimed. But i wanna ask if we make reverse search like a youtube channel to email ? Thank you for attention.

**Comment by mxrch** [comment]
Hello @5l1v3r1 , we can't. 😕 
Just pray for an email in the about section or getting usernames to guess the email.

**Comment by kuldeepkumar2330** [comment]
> Thank you for the great tool. It works flawlessly as it is claimed. But i wanna ask if we make reverse search like a youtube channel to email ? Thank you for attention.

#80

**Comment by kuldeepkumar2330** [comment]
> Hello @5l1v3r1 , we can't. 😕 
> Just pray for an email in the about section or getting usernames to guess the email.

#80

**Comment by 5l1v3r1** [comment]
well i think still might be possible. Please take a look at that one. https://regex101.com/r/5TBgN1/1
