### ISSUE TITLE
error after validating cookies ">PermissionError: [Errno 13] Permission denied: 'resources/data.txt'"

### ISSUE THREAD

**Issue by devXghost** [mxrch/GHunt#85]
<code> sudo docker run -v $(pwd)/resources:/usr/src/app/resources -ti ghunt check_and_gen.py </code>
..
>[+] The cookies seems valid! Generating the Google Docs and Hangouts token...
>
>Google Docs Token => AC4w5VgYNP3YfbwYY4l..
>Authorization Token => SAPISIDHASH 16023705..
>Hangouts Token => AIzaSyD7InnYR3VKdb4j2..
>Traceback (most recent call last):
>	File "check_and_gen.py", line 130, in <module>
>	save_tokens(auth_token, gdoc_token, hangouts_token, cookies)
>	File "check_and_gen.py", line 48, in save_tokens
>	with open(config.data_path, 'w') as f:
>PermissionError: [Errno 13] Permission denied: 'resources/data.txt'

**Comment by luizlc** [comment]
I have the same problem  :(

**Comment by devXghost** [comment]
I don't have this issue anymore, in fact, I didn't execute the correct docker run command as indicated in the readme file, my comand was missing <code>  --build-arg UID=$(id -u ${USER}) --build-arg GID=$(id -g ${USER})  </code>
