### ISSUE TITLE
In Termux not working

### ISSUE THREAD

**Issue by GeorgNation** [mxrch/GHunt#86]
I tried to install GHunt on my phone via Termux, but when installing packages, this appears![Screenshot_2020-10-11-21-17-27-011_com.termux.jpg](https://user-images.githubusercontent.com/55389952/95682710-955b6a80-0c08-11eb-92db-8a5e5fde1d65.jpg)

**Comment by GeorgNation** [comment]
![Screenshot_2020-10-11-21-28-00-396_com.termux.jpg](https://user-images.githubusercontent.com/55389952/95682722-a6a47700-0c08-11eb-8574-3a32ed0e2904.jpg)

**Comment by GeorgNation** [comment]
Python 3.9.0, pip3 install -r requirements.txt

**Comment by coderj001** [comment]
Try to go through this termux [wiki](https://wiki.termux.com/wiki/Python#Python_module_installation_tips_and_tricks).

**Comment by GeorgNation** [comment]
the error occurs when installing skipy.

**Comment by GeorgNation** [comment]
the error occurs when installing scipy

**Comment by mxrch** [comment]
Yeah, Termux is not supported for now.

**Comment by diehard88** [comment]
check #497
