### ISSUE TITLE
Linux Mint reqirements install error

### ISSUE THREAD

**Issue by JanuszSpiewa** [mxrch/GHunt#88]
Hi 

I dont run GHunt 

`pip install -r requirements.txt
Collecting geopy (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/41/4e/a3eb6ac14a9c4344d6f5e66a9457d82cf124daf5c8176cec0a49677b0e03/geopy-1.23.0-py2.py3-none-any.whl (120kB)
    100% |################################| 122kB 658kB/s 
Collecting httpx (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement httpx (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for httpx (from -r requirements.txt (line 2))

`

**Comment by mxrch** [comment]
@JanuszSpiewa  Which python version are you running and on which operating system are you ?

**Comment by JanuszSpiewa** [comment]
python 3.8 

OS: Linux mint 19.3

**Comment by Timodz** [comment]
I hade a similar issue in Linux Mint 19, the solution was to upgrade pip and install again
`pip install --upgrade pip`

and make sure that pip is from a 3.x python version by using this command since for me I hade to use pip3 since pip was using python 2.7
`pip -V`

**Comment by mxrch** [comment]
Yes, the best practise is to use `python3 -m pip`, thank you for your feedback @Timodz .
