### ISSUE TITLE
[-] This email address does not belong to a Google Account.

### ISSUE THREAD

**Issue by hetmehtaa** [mxrch/GHunt#92]
$ python3 hunt.py myemail@gmail.com

 
     .d8888b.  888    888                   888    
    d88P  Y88b 888    888                   888    
    888    888 888    888                   888    
    888        8888888888 888  888 88888b.  888888 
    888  88888 888    888 888  888 888 "88b 888    
    888    888 888    888 888  888 888  888 888    
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.  
     "Y8888P88 888    888  "Y88888 888  888  "Y888
    
[-] This email address does not belong to a Google Account.

**Comment by mxrch** [comment]
Yes, this means this email doesn't exists.
You can test with various simple names like email@gmail.com, google@gmail.com, admin@gmail.com, trump@gmail.com, I think Google just blocks some dangerous names that can be used for phishing or something like that.
