### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'resources/data.txt'

### ISSUE THREAD

**Issue by luizlc** [mxrch/GHunt#93]
Can you help me with this error?

Google Docs Token => AC4w5VhNtjx23lAT8OXxC6Bns9EAzHg5Yg:160266128
Authorization Token => SAPISIDHASH 1602661292_efb1c0fa30e8db1dc170a4b26798d4941f6e
Hangouts Token => AIzaSyD7InnYR3VKdb4j2Ir2VyEazl6k
Traceback (most recent call last):
  File "check_and_gen.py", line 97, in <module>
    with open(cfg['data_path'], 'w') as f:
PermissionError: [Errno 13] Permission denied: 'resources/data.txt'
┌─[✗]─[parrot@parrot]─[~/GHunt]

**Comment by PinkDev1** [comment]
Does `resources/data.txt` exist?
if so, do:
```
sudo chown parrot resources/data.txt
sudo chmod 777 resources/data.txt
```

I should also mention that a similar fix can probably be used on #94 and #96
