### ISSUE TITLE
Doesn't belong to a Google Account

### ISSUE THREAD

**Issue by MarCus-8421** [mxrch/GHunt#99]
I am giving a good account , still it is saying email doesn't belong to a Google account !! 
![IMG_20201015_053814](https://user-images.githubusercontent.com/65368585/96058385-a9bd9280-0ea8-11eb-9c9a-39217a9de88c.jpg)

**Comment by 0xTen** [comment]
same here...

**Comment by mxrch** [comment]
![image](https://user-images.githubusercontent.com/17338428/97084152-4a345500-1615-11eb-9236-e7ae4cbdd004.png)
 It's working for me.
Can you retry with the last updates ?
